"""`utils/producer_template.py` 的单测：HTTP / 维基全部 mock，不联网。"""
import json
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from utils import producer_template as pt


class _Response:
    def __init__(self, payload, cookies=None):
        self.text = json.dumps(payload) if not isinstance(payload, str) else payload
        self.status_code = 200
        # b 站搜索要 cookie（`bilibili_cookies()` 从预热响应里读），所以这里也带一份
        self.cookies = dict(cookies or {})

    def raise_for_status(self):
        return None

    def json(self):
        return json.loads(self.text)


def _patch_get(routes):
    """按 url 前缀分发假响应；返回 mock 出来的 `http_get`。"""

    def fake_get(url, use_proxy=False, params=None, timeout=None, **kwargs):
        for prefix, payload in routes.items():
            if url.startswith(prefix):
                if callable(payload):
                    return _Response(payload(params or {}))
                return _Response(payload)
        raise AssertionError(f"没准备好这个地址的假响应：{url}")

    return mock.patch.object(pt, "http_get", side_effect=fake_get)


SONG_ITEM = {
    "id": 1, "defaultName": "天堂", "artistString": "雄之助 feat. 初音ミク",
    "publishDate": "2024-08-28T00:00:00Z", "songType": "Original",
}


class ParseHelpersTest(unittest.TestCase):
    def test_clean_title(self):
        self.assertEqual(pt.clean_title("{{lj|ループメモリー}}"), "ループメモリー")
        self.assertEqual(pt.clean_title("{{lj|[[时滞记录|ラグタイムレコード]]}}"), "ラグタイムレコード")
        self.assertEqual(pt.clean_title("[[中文|日文]]"), "日文")
        self.assertEqual(pt.clean_title("超新星{{!}}Supernova"), "超新星")
        self.assertEqual(pt.clean_title("<!--\n-->Navy<!--\n-->"), "Navy")
        self.assertEqual(pt.clean_title("'''粗体'''"), "粗体")

    def test_template_calls_handles_nesting(self):
        text = "{{lj|{{links|A{{!}}B|C}}}}"
        self.assertEqual(pt.template_calls(text, "links"), ["A{{!}}B|C"])

    def test_split_args_ignores_nested_pipes(self):
        self.assertEqual(pt.split_args("A{{!}}B|{{lj|C}}|D"), ["A{{!}}B", "{{lj|C}}", "D"])

    def test_parse_publish_date(self):
        self.assertEqual(pt.parse_publish_date("2026-08-28T00:00:00Z"), "2026-08-28")
        self.assertEqual(pt.parse_publish_date("2024-08"), "2024-08")
        self.assertEqual(pt.parse_publish_date("2024"), "2024")
        self.assertEqual(pt.parse_publish_date(None), "")
        self.assertEqual(pt.parse_publish_date("不是日期"), "")

    def test_parse_artist_id(self):
        self.assertEqual(pt.parse_artist_id("23981"), 23981)
        self.assertEqual(pt.parse_artist_id("https://vocadb.net/Artist/Details/23981"), 23981)
        self.assertEqual(pt.parse_artist_id("雄之助"), 0)


class AutoUploadTest(unittest.TestCase):
    """只有发行商代传的 YouTube 自动投稿的曲子不收（用户 2026-10 要求）。

    实测 S/950828（ワープループ）：唯一的 PV 是 `author = "Yunosuke - Topic"`、
    简介 `Provided to YouTube by NexTone Inc. … Auto-generated by YouTube.`。
    """

    TOPIC = {"service": "Youtube", "author": "Yunosuke - Topic",
             "description": "Provided to YouTube by NexTone Inc.\n\nワープループ\n\n"
                            "Auto-generated by YouTube."}
    REAL = {"service": "NicoNicoDouga", "author": "雄之助", "description": "新曲です"}

    def test_is_auto_upload(self):
        self.assertTrue(pt.is_auto_upload(self.TOPIC))
        self.assertTrue(pt.is_auto_upload({"author": "雄之助 - Topic"}))
        self.assertTrue(pt.is_auto_upload({"description": "Provided to YouTube by X"}))
        self.assertTrue(pt.is_auto_upload({"description": "Auto-generated by YouTube."}))
        self.assertFalse(pt.is_auto_upload(self.REAL))
        self.assertFalse(pt.is_auto_upload({}))

    def test_has_real_pv(self):
        self.assertFalse(pt.has_real_pv({"pvs": [self.TOPIC]}))
        self.assertTrue(pt.has_real_pv({"pvs": [self.TOPIC, self.REAL]}))   # 混着就保留
        self.assertTrue(pt.has_real_pv({"pvs": [self.REAL]}))
        self.assertTrue(pt.has_real_pv({}))                                   # 没信息就不删

    def test_fetch_songs_skips_auto_upload_only_songs(self):
        payload = {"items": [
            {**SONG_ITEM, "id": 1, "defaultName": "ワープループ", "pvs": [self.TOPIC]},
            {**SONG_ITEM, "id": 2, "defaultName": "ネハン",
             "pvs": [self.TOPIC, self.REAL]},
            {**SONG_ITEM, "id": 3, "defaultName": "没有 PV 信息"},
        ]}
        with _patch_get({pt.VOCADB_SONG_URL: payload}):
            songs = pt.fetch_songs(23981)
        self.assertEqual(["ネハン", "没有 PV 信息"], [song.ja for song in songs])


class OwnAlbumTest(unittest.TestCase):
    """合辑 / 多艺人发行 / 只是挂名支持的专辑不收（用户 2026-10 要求）。"""

    def test_various_artists_is_not_ours(self):
        # Al/55475「音速を超えて」、Al/54757「NIGHT HIKE Compilation Vol.1」
        for name in ("音速を超えて", "NIGHT HIKE Compilation Vol.1"):
            self.assertFalse(pt.is_own_album(
                {"name": name, "artistString": "Various artists", "artists": [
                    {"artist": {"id": 23981}, "isSupport": False, "roles": "Default"}]},
                23981))

    def test_support_only_credits_are_not_ours(self):
        self.assertFalse(pt.is_own_album(
            {"name": "hologram", "artistString": "Ruliea feat. various", "artists": [
                {"artist": {"id": 123110}, "isSupport": False, "roles": "Default"},
                {"artist": {"id": 23981}, "isSupport": True, "roles": "Arranger"}]},
            23981))

    def test_own_albums_are_kept(self):
        self.assertTrue(pt.is_own_album(
            {"name": "Void", "artistString": "雄之助 feat. various", "artists": [
                {"artist": {"id": 23981}, "isSupport": False, "roles": "Default"}]},
            23981))
        # 没有 artistString / artists 时一律保留（宁可多留，不要误删）
        self.assertTrue(pt.is_own_album({"name": "Void"}, 23981))
        # 艺人列表里没有他 → 也不能因此当作「只是挂名」
        self.assertTrue(pt.is_own_album(
            {"name": "Void", "artistString": "Yunosuke",
             "artists": [{"artist": {"id": 999}, "isSupport": False}]}, 23981))

    def test_fetch_albums_filters_and_dedupes(self):
        payload = {"items": [
            {"name": "Void", "releaseDate": {"year": 2025},
             "artistString": "雄之助 feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "音速を超えて", "releaseDate": {"year": 2026},
             "artistString": "Various artists",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "hologram", "releaseDate": {"year": 2024},
             "artistString": "Ruliea feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": True}]},
            {"name": "Pathos", "releaseDate": {"year": 2016},
             "artistString": "雄之助, 攻 feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "Void", "releaseDate": {"year": 2025},
             "artistString": "雄之助 feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "", "releaseDate": {"year": 2020}},
        ]}
        with _patch_get({pt.VOCADB_ALBUM_URL: payload}) as get:
            albums = pt.fetch_albums(23981)
        self.assertEqual(["Pathos", "Void"], albums)
        self.assertEqual("Album", get.call_args.kwargs["params"]["discTypes"])
        self.assertEqual(23981, get.call_args.kwargs["params"]["artistId[]"])
        self.assertIn("Artists", get.call_args.kwargs["params"]["fields"])


class AvatarTest(unittest.TestCase):
    """P主头像（`utils/producer_template.py`）：当「样式」页的默认参考图。

    用户 2026-10 要求「选择参考图默认选择 P主头像下载并交给 AI 生成 CSS」。
    """

    URL = "https://static.vocadb.net/img/Artist/mainOrig/23981.jpg?v=37"

    def _artist(self, picture: str = URL) -> pt.ProducerArtist:
        return pt.ProducerArtist(id=23981, name="雄之助", artist_type="Producer",
                                 picture=picture)

    def test_to_artist_reads_the_main_picture(self):
        artist = pt._to_artist({"id": 23981, "name": "雄之助", "artistType": "Producer",
                                "mainPicture": {"urlOriginal": self.URL,
                                                "urlThumb": "https://x/thumb.jpg"}})
        self.assertEqual(self.URL, artist.picture)
        # 只有缩略图时退到缩略图
        thumb = pt._to_artist({"id": 1, "name": "A",
                               "mainPicture": {"urlTinyThumb": "https://x/tiny.jpg"}})
        self.assertEqual("https://x/tiny.jpg", thumb.picture)
        self.assertEqual("", pt._to_artist({"id": 1, "name": "A"}).picture)
        self.assertEqual("", pt._to_artist({"id": 1, "name": "A", "mainPicture": None}).picture)

    def test_artist_requests_the_main_picture_field(self):
        """实测：不传 `fields=MainPicture` 时响应里只有 `pictureMime`，没有地址。"""
        payload = {"id": 23981, "name": "雄之助"}
        with _patch_get({f"{pt.VOCADB_ARTIST_URL}/23981": payload}) as get:
            pt.fetch_artist(23981)
        self.assertEqual(pt.ARTIST_FIELDS, get.call_args.kwargs["params"]["fields"])
        with _patch_get({pt.VOCADB_ARTIST_URL: {"items": [payload]}}) as get:
            pt.search_artists("雄之助")
        self.assertEqual(pt.ARTIST_FIELDS, get.call_args.kwargs["params"]["fields"])

    def test_avatar_filename(self):
        self.assertEqual("P主头像_雄之助.jpg", pt.avatar_filename(self._artist()))
        # 地址里没有扩展名 / 没有头像时退回 .jpg（AI 那边按后缀判 mime）
        self.assertEqual("P主头像_雄之助.jpg",
                         pt.avatar_filename(self._artist("https://x/mainOrig/23981")))
        self.assertEqual("P主头像_雄之助.jpg", pt.avatar_filename(self._artist("")))
        self.assertEqual("P主头像_雄之助.jpg",
                         pt.avatar_filename(pt.ProducerArtist(id=1, name="雄之助")))

    def test_download_avatar_writes_into_the_output_folder(self):
        with tempfile.TemporaryDirectory() as folder:
            def fake_download(url, target):
                Path(target).write_bytes(b"x" * 32)
                return True

            with mock.patch.object(pt.image, "download_file",
                                   side_effect=fake_download) as download:
                path = pt.download_avatar(self._artist(), folder)
            target = Path(folder) / "P主头像_雄之助.jpg"
            self.assertEqual(target, path)
            self.assertTrue(path.is_file())
            download.assert_called_once_with(self.URL, target)
            # 已经下过就直接用现成的，不重复下载
            with mock.patch.object(pt.image, "download_file") as again:
                self.assertEqual(target, pt.download_avatar(self._artist(), folder))
            again.assert_not_called()

    def test_download_avatar_without_a_picture(self):
        with mock.patch.object(pt.image, "download_file") as download:
            self.assertIsNone(pt.download_avatar(self._artist(""), tempfile.mkdtemp()))
            self.assertIsNone(pt.download_avatar(pt.ProducerArtist(id=1, name="A")))
        download.assert_not_called()

    def test_download_avatar_swallows_errors(self):
        with tempfile.TemporaryDirectory() as folder, \
                mock.patch.object(pt.image, "download_file", side_effect=RuntimeError("boom")):
            self.assertIsNone(pt.download_avatar(self._artist(), folder))


class VocaDbTest(unittest.TestCase):
    def test_search_artists_by_name(self):
        payload = {"items": [{"id": 23981, "name": "雄之助", "artistType": "Producer",
                              "additionalNames": "Yunosuke"}]}
        with _patch_get({pt.VOCADB_ARTIST_URL: payload}) as get:
            artists = pt.search_artists("雄之助")
        self.assertEqual(len(artists), 1)
        self.assertEqual(artists[0].id, 23981)
        self.assertEqual(artists[0].name_en, "Yunosuke")
        # 名字搜索走 query，不该带 artistId
        self.assertEqual(get.call_args.kwargs["params"]["query"], "雄之助")

    def test_search_artists_by_url_goes_to_details(self):
        payload = {"id": 23981, "name": "雄之助", "artistType": "Producer"}
        with _patch_get({f"{pt.VOCADB_ARTIST_URL}/23981": payload}) as get:
            artists = pt.search_artists("https://vocadb.net/Artist/Details/23981")
        self.assertEqual(artists[0].name, "雄之助")
        self.assertTrue(get.call_args.args[0].endswith("/artists/23981"))

    def test_search_artists_empty_query(self):
        self.assertEqual(pt.search_artists("  "), [])

    def test_fetch_songs_uses_array_param_and_sorts(self):
        pages = {}

        def handler(params):
            pages["params"] = params
            return {"items": [SONG_ITEM,
                              {**SONG_ITEM, "id": 2, "defaultName": "早安",
                               "publishDate": "2020-01-01T00:00:00Z"}]}

        with _patch_get({pt.VOCADB_SONG_URL: handler}):
            songs = pt.fetch_songs(23981)
        self.assertEqual([s.ja for s in songs], ["早安", "天堂"])       # 按日期从早到晚
        self.assertEqual(pages["params"]["artistId[]"], 23981)
        self.assertEqual(pages["params"]["songTypes"], "Original")
        self.assertEqual(pages["params"]["onlyWithPvs"], "true")
        self.assertNotIn("artistId", pages["params"])                # 写成 artistId 会被静默忽略

    def test_fetch_songs_dedupes_and_pages(self):
        calls = []

        def handler(params):
            calls.append(params["start"])
            if params["start"] == 0:
                return {"items": [SONG_ITEM] * 100}
            return {"items": [{**SONG_ITEM, "id": 3, "defaultName": "再来",
                               "publishDate": "2026-01-01T00:00:00Z"}]}

        with _patch_get({pt.VOCADB_SONG_URL: handler}):
            songs = pt.fetch_songs(23981)
        self.assertEqual(calls, [0, 100])
        self.assertEqual([s.ja for s in songs], ["天堂", "再来"])

    def test_fetch_works_without_artist(self):
        with _patch_get({pt.VOCADB_ARTIST_URL: {"items": []}}):
            work = pt.fetch_works("不存在的人")
        self.assertEqual(work.songs, [])
        self.assertEqual(work.artist.name, "")


class ProducerPageTest(unittest.TestCase):
    PAGE = """== 歌曲 ==
{{Producer_Song
|nnd_id   = sm45871877
|作曲     = {{lj|はるまきごはん}}
|投稿日期 = 2025年8月21日
|条目     = 揉揉头
|标题     = {{lj|アタマモミ}}
|image    = x.jpg
}}

{{Producer_Song
|条目     = 时滞记录
|标题     = {{lj|[[时滞记录|ラグタイムレコード]]}}
}}

* 专辑：《[[#Void|Void]]》与 [[#Pathos|Pathos]]
{{lj|[[银河录|{{lj|銀河録}}]]}}
"""

    # 歌曲条目一定带信息框（实测：VOCALOID Songbox / VOCALOID_Songbox）
    SONG_PAGE = "{{VOCALOID Songbox\n|标题 = ラグタイムレコード\n}}\n'''ラグタイムレコード''' 即时滞记录。"
    # 榜单页：正文写着歌名，但没有信息框 —— 不是歌曲条目（实测第 87 期用的就是 {{Billboard}}）
    RANKING_PAGE = ("{{Billboard|index=87}}\n{| class=\"wikitable\"\n|-\n"
                    "| 1 || [[ラグタイムレコード]] || はるまきごはん\n|}")

    def test_parse_producer_page(self):
        mapping = pt.parse_producer_page(self.PAGE)
        self.assertEqual(mapping["アタマモミ"], "揉揉头")
        self.assertEqual(mapping["ラグタイムレコード"], "时滞记录")
        self.assertEqual(mapping["銀河録"], "银河录")
        self.assertNotIn("Void", mapping)          # `[[#Void|Void]]` 是专辑小节，不是条目
        self.assertNotIn("Pathos", mapping)

    def test_apply_wiki_names(self):
        songs = [pt.ProducerSong(ja="アタマモミ"), pt.ProducerSong(ja="未知的歌"),
                 pt.ProducerSong(ja="アタマモミ", cn="已填的")]
        filled = pt.apply_wiki_names(songs, {"アタマモミ": "揉揉头"})
        self.assertEqual(filled, 1)
        self.assertEqual(songs[0].cn, "揉揉头")
        self.assertEqual(songs[2].cn, "已填的")     # 已经填过的不覆盖

    def test_merge_page_songs_adds_wiki_only_songs(self):
        work = pt.ProducerWork(songs=[pt.ProducerSong(ja="アタマモミ", date="2025-08-21")])
        pt._merge_page_songs(work, self.PAGE)
        names = [s.ja for s in work.songs]
        self.assertIn("ラグタイムレコード", names)          # 页面上有、VocaDB 没给
        self.assertEqual(names.count("アタマモミ"), 1)      # 重复的不再加一遍
        added = [s for s in work.songs if s.ja == "ラグタイムレコード"][0]
        self.assertEqual(added.source, "wiki")

    def test_mark_existing_fills_chinese_name(self):
        songs = [pt.ProducerSong(ja="ラグタイムレコード"), pt.ProducerSong(ja="不存在")]
        pt.mark_existing(songs, {"时滞记录": "正文"})
        self.assertFalse(songs[0].page_exists)
        pt.mark_existing([pt.ProducerSong(ja="タイトル")], {"タイトル": "正文"})
        songs = [pt.ProducerSong(ja="ラグタイムレコード", cn="时滞记录")]
        pt.mark_existing(songs, {"时滞记录": "正文"})
        self.assertTrue(songs[0].page_exists)

    def test_resolve_from_wiki(self):
        work = pt.ProducerWork(artist=pt.ProducerArtist(id=1, name="雄之助"),
                               songs=[pt.ProducerSong(ja="ラグタイムレコード"),
                                      pt.ProducerSong(ja="Navy")])
        texts = {"雄之助": self.PAGE, "时滞记录": "正文", "Navy": "正文"}
        with mock.patch.object(pt.wiki_api, "fetch_pages_text",
                               side_effect=lambda titles: {t: texts[t] for t in titles
                                                           if t in texts}):
            pt.resolve_from_wiki(work)
        self.assertEqual(work.page_name, "雄之助")
        by_ja = {song.ja: song for song in work.songs}
        self.assertEqual(by_ja["ラグタイムレコード"].cn, "时滞记录")
        self.assertEqual(by_ja["アタマモミ"].cn, "揉揉头")          # 从 P主条目里补进来的
        self.assertEqual(by_ja["アタマモミ"].date, "2025-08-21")   # 日期也来自 {{Producer_Song}}

    def test_search_page_by_song_prefers_page_with_japanese_name(self):
        result = [("雄之助", "别的"), ("时滞记录", self.SONG_PAGE)]
        with mock.patch.object(pt.wiki_api, "search_pages_with_text",
                               return_value=result):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")),
                             "时滞记录")
        with mock.patch.object(pt.wiki_api, "search_pages_with_text", return_value=[]):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")), "")

    def test_looks_like_song_page_needs_a_songbox(self):
        """歌曲条目都带 `{{…Songbox}}`；榜单页 / 专辑页 / P主页面 / 消歧义页都不带。"""
        self.assertTrue(pt.looks_like_song_page(self.SONG_PAGE))
        self.assertTrue(pt.looks_like_song_page("{{VOCALOID_Songbox\n|标题 = 时滞记录\n}}"))
        self.assertTrue(pt.looks_like_song_page("{{VOCALOID songbox}}"))     # 不区分大小写
        self.assertFalse(pt.looks_like_song_page(self.RANKING_PAGE))
        self.assertFalse(pt.looks_like_song_page("{{Album Infobox}}"))
        self.assertFalse(pt.looks_like_song_page("{{disambig}}"))
        self.assertFalse(pt.looks_like_song_page("{{Producer_Song|条目=随便}}"))
        self.assertFalse(pt.looks_like_song_page(""))
        self.assertFalse(pt.looks_like_song_page(None))

    def test_search_page_by_song_skips_pages_without_songbox(self):
        """用户 2026-10 报「中文名会变成 NICONICO VOCALOID SONGS TOP20/第87期」。

        实测那一页是 Billboard 榜单（用 `{{Billboard}}`），**正文里确实写着歌名**、
        可它没有 Songbox，不是歌曲条目 —— 以前只核对「正文提没提到日文名」，
        就把榜单页的标题当成中文条目名填进去了，模板最后还链到了榜单上。
        """
        ranking = ("NICONICO VOCALOID SONGS TOP20/第87期", self.RANKING_PAGE)
        with mock.patch.object(pt.wiki_api, "search_pages_with_text",
                               return_value=[ranking, ("时滞记录", self.SONG_PAGE)]):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")),
                             "时滞记录")
        with mock.patch.object(pt.wiki_api, "search_pages_with_text",
                               return_value=[ranking]):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")), "")

    def test_fill_missing_names(self):
        songs = [pt.ProducerSong(ja="已填", cn="已填"), pt.ProducerSong(ja="要找"),
                 pt.ProducerSong(ja="找不到")]
        seen = []
        with mock.patch.object(pt, "search_page_by_song",
                               side_effect=lambda song: "找到的页" if song.ja == "要找" else ""):
            filled = pt.fill_missing_names(songs, progress=seen.append)
        self.assertEqual(filled, 1)
        self.assertEqual(songs[1].cn, "找到的页")
        self.assertTrue(any("要找" in line for line in seen))


class ExternalNameTest(unittest.TestCase):
    """外部来源搜中文名（`bilibili` / 网易云）：解析、来源可信度、维基核实、批量填充。

    用户 2026-10 要求「曲目」页能「从外部链接获取中文名」。
    """

    def setUp(self):
        # b 站 cookie 是模块级缓存：每条用例都从「没预热过」开始
        patcher = mock.patch.object(pt, "_bili_cookies", None)
        patcher.start()
        self.addCleanup(patcher.stop)

    def test_is_chinese_name(self):
        self.assertTrue(pt.is_chinese_name("时滞记录"))
        self.assertTrue(pt.is_chinese_name("揉揉头"))
        self.assertFalse(pt.is_chinese_name("ラグタイムレコード"))       # 假名 = 日文名
        self.assertFalse(pt.is_chinese_name("Void"))                  # 没汉字
        self.assertFalse(pt.is_chinese_name("这首歌不该只在我的循环列表里发光"))  # 太长
        self.assertFalse(pt.is_chinese_name("挺好听的，推荐一下。"))      # 一句话
        self.assertFalse(pt.is_chinese_name(""))

    def test_clean_name_strips_decorations(self):
        self.assertEqual("忧蓝情结", pt.clean_name("【中文字幕】忧蓝情结"))
        self.assertEqual("涅槃", pt.clean_name("《涅槃》"))
        self.assertEqual("涅槃", pt.clean_name("涅槃 feat. 重音テト"))

    def test_chinese_from_title_prefers_the_name_next_to_the_japanese(self):
        """实测：`【中文字幕】忧蓝情结/ブルー・マニアック feat.初音ミク【ナルネア】`。"""
        title = "【中文字幕】忧蓝情结/ブルー・マニアック feat.初音ミク【ナルネア】"
        self.assertEqual(("忧蓝情结", True), pt.chinese_from_title(title, "ブルー・マニアック"))

    def test_chinese_from_title_drops_the_producer_name(self):
        """`ネハン / 雄之助 feat. 重音テトSV` 是 N 站本家的写法，里面没有中文名。"""
        self.assertEqual(("", False),
                         pt.chinese_from_title("ネハン / 雄之助 feat. 重音テトSV", "ネハン", "雄之助"))

    def test_chinese_from_title_drops_noise_segments(self):
        title = "【中日歌词】indigo la End『ワールプール』自制PV"
        self.assertEqual(("", False), pt.chinese_from_title(title, "ワープループ"))

    def test_chinese_from_netease_wants_a_matching_entry(self):
        """只有「自己名字里有这首歌」或「署名里有这个 P主」的条目才算对得上。"""
        matched = {"name": "ネハン (feat. 重音テト)", "artists": [{"name": "雄之助"}],
                   "transNames": ["涅槃"]}
        self.assertEqual(["涅槃"], pt.chinese_from_netease(matched, "ネハン", "雄之助"))
        # 搜「さよなら天才」实测会返回一堆无关的歌（网易云按相关度硬凑）
        unrelated = {"name": "Chase The Wind", "artists": [{"name": "コア"}]}
        self.assertEqual([], pt.chinese_from_netease(unrelated, "さよなら天才", "雄之助"))

    def test_chinese_from_netease_reads_alias_and_chinese_name(self):
        """网易云上有的条目直接写中文名（名字里没有日文原名），只能靠 P主 认。"""
        item = {"name": "揉揉头", "artists": [{"name": "はるまきごはん"}], "alias": ["アタマモミ"]}
        self.assertEqual(["揉揉头"], pt.chinese_from_netease(item, "アタマモミ", "はるまきごはん"))

    def test_pick_candidate_needs_wiki_verification_for_bilibili(self):
        """b 站标题里抽出来的名字必须核实：实测 さよなら天才 的标题能抽出「高潮部分真的好棒」。"""
        candidates = [("高潮部分真的好棒", pt.SOURCE_BILIBILI, 2)]
        self.assertIsNone(pt.pick_candidate(candidates, {}))
        # 站上真有这个歌曲条目 → 才认
        verified = {"再见天才": "{{VOCALOID Songbox}}\n正文"}
        self.assertEqual(("再见天才", pt.SOURCE_BILIBILI),
                         pt.pick_candidate([("再见天才", pt.SOURCE_BILIBILI, 2)], verified))
        # 页面存在但不是歌曲条目（榜单页 / P主页面）→ 不算
        self.assertIsNone(pt.pick_candidate([("高潮部分真的好棒", pt.SOURCE_BILIBILI, 2)],
                                            {"高潮部分真的好棒": "{{Producer_Song}}"}))

    def test_pick_candidate_takes_netease_name_without_verification(self):
        """网易云的结构化译名（transNames / alias）可以直接用。"""
        candidates = [("忧蓝情结", pt.SOURCE_NETEASE, 3)]
        self.assertEqual(("忧蓝情结", pt.SOURCE_NETEASE), pt.pick_candidate(candidates, {}))

    def test_pick_candidate_prefers_the_verified_page(self):
        candidates = [("忧蓝情结", pt.SOURCE_NETEASE, 3), ("蓝琥珀", pt.SOURCE_BILIBILI, 1)]
        texts = {"蓝琥珀": "{{VOCALOID_Songbox}}"}
        self.assertEqual(("蓝琥珀", pt.SOURCE_BILIBILI), pt.pick_candidate(candidates, texts))

    def test_fill_external_names_fills_and_counts_by_source(self):
        songs = [pt.ProducerSong(ja="ネハン"), pt.ProducerSong(ja="ブルー・マニアック"),
                 pt.ProducerSong(ja="已填", cn="已填")]
        seen: List[str] = []
        with mock.patch.object(pt, "external_candidates",
                               side_effect=lambda song, artist="": {
                                   "ネハン": [("涅槃", pt.SOURCE_NETEASE, 3)],
                                   "ブルー・マニアック": [("忧蓝情结", pt.SOURCE_BILIBILI, 2)],
                               }.get(song.ja, [])), \
                mock.patch.object(pt.wiki_api, "fetch_pages_text",
                                  return_value={"涅槃": "{{VOCALOID Songbox}}"}):
            result = pt.fill_external_names(songs, "雄之助", progress=seen.append)
        self.assertEqual(1, result["filled"])
        self.assertEqual({"网易云": 1}, result["by_source"])        # b 站那个没核实到 → 不填
        self.assertEqual("涅槃", songs[0].cn)
        self.assertTrue(songs[0].page_exists)
        self.assertEqual("", songs[1].cn)
        self.assertTrue(any("ネハン" in line for line in seen))

    def test_fill_external_names_skips_songs_that_already_have_names(self):
        songs = [pt.ProducerSong(ja="A", cn="甲"), pt.ProducerSong(ja="")]
        with mock.patch.object(pt, "external_candidates") as candidates:
            result = pt.fill_external_names(songs, "雄之助")
        candidates.assert_not_called()
        self.assertEqual(0, result["filled"])
        self.assertEqual(0, result["checked"])

    def test_netease_search_parses_songs(self):
        payload = {"code": 200, "result": {"songs": [{"name": "ネハン"}]}}
        with _patch_get({pt.NETEASE_SEARCH_API: payload}):
            self.assertEqual([{"name": "ネハン"}], pt.netease_search("ネハン"))

    def test_netease_search_swallows_errors(self):
        with mock.patch.object(pt, "http_get", side_effect=RuntimeError("boom")):
            self.assertEqual([], pt.netease_search("ネハン"))

    def test_bilibili_search_warms_cookies_and_retries_on_412(self):
        """实测：不带 cookie 时接口直接 412（返回 HTML），带上 `buvid3` 才是 JSON。"""
        calls: List[str] = []
        payloads = [{"code": -412, "message": "请求被拦截"},
                    {"code": 0, "data": {"result": [{"title": "涅槃/ネハン"}]}}]

        def fake_get(url, use_proxy=False, params=None, timeout=None, **kwargs):
            calls.append(url)
            if url == pt.BILIBILI_HOME:
                return _Response("<html/>", cookies={"buvid3": "abc", "b_nut": "1"})
            return _Response(payloads.pop(0))

        with mock.patch.object(pt, "http_get", side_effect=fake_get):
            self.assertEqual(["涅槃/ネハン"], pt.bilibili_search("ネハン"))
        # 预热 → 搜索（412）→ 重新预热 → 搜索（成功）
        self.assertEqual([pt.BILIBILI_HOME, pt.BILIBILI_SEARCH_API,
                          pt.BILIBILI_HOME, pt.BILIBILI_SEARCH_API], calls)

    def test_bilibili_cookies_are_warmed_once(self):
        calls: List[str] = []

        def fake_get(url, use_proxy=False, params=None, timeout=None, **kwargs):
            calls.append(url)
            if url == pt.BILIBILI_HOME:
                return _Response("<html/>", cookies={"buvid3": "abc"})
            return _Response({"code": 0, "data": {"result": []}})

        with mock.patch.object(pt, "http_get", side_effect=fake_get):
            pt.bilibili_search("A")
            pt.bilibili_search("B")
        # 两个关键词只预热一次（原来每首多一次请求）
        self.assertEqual([pt.BILIBILI_HOME, pt.BILIBILI_SEARCH_API,
                          pt.BILIBILI_SEARCH_API], calls)


class BuildTemplateTest(unittest.TestCase):
    def _work(self) -> pt.ProducerWork:
        return pt.ProducerWork(
            artist=pt.ProducerArtist(id=1, name="雄之助"),
            songs=[pt.ProducerSong(ja="天堂", cn="天堂中文", date="2024-08-28"),
                   pt.ProducerSong(ja="Navy", date="2024-01-05"),
                   pt.ProducerSong(ja="ラグタイムレコード", cn="时滞记录", date="2021-09-01"),
                   pt.ProducerSong(ja="没日期")],
            albums=["Void", "Pathos"], page_name="雄之助", template_name="雄之助")

    def test_song_link_forms(self):
        self.assertEqual(pt.ProducerSong(ja="天堂", cn="天堂中文").link(), "天堂中文{{!}}{{lj|天堂}}")
        self.assertEqual(pt.ProducerSong(ja="Navy").link(), "Navy")
        self.assertEqual(pt.ProducerSong(ja="ラグタイムレコード").link(), "ラグタイムレコード")
        self.assertEqual(pt.ProducerSong(ja="", cn="只有中文").link(), "只有中文")

    def test_build_song_groups(self):
        groups = pt.build_song_groups(self._work().songs)
        self.assertEqual([label for label, _ in groups], ["2021", "2024", "其他"])
        self.assertEqual([len(songs) for _label, songs in groups], [1, 2, 1])

    def test_style_params(self):
        params = pt.style_params({**pt.DEFAULT_STYLES, "listBg": "#FFF", "listFg": ""})
        self.assertEqual(params["titlestyle"], "background:#94ceda;color:#006cad")
        self.assertEqual(params["liststyle"], "background:#FFF")
        self.assertEqual(pt.style_params({"titleBg": "", "titleFg": ""})["titlestyle"], "")

    def test_build_template_structure(self):
        text = pt.build_template(self._work())
        self.assertIn("[[分类:P主模板]]", text)
        self.assertIn("|name=雄之助", text)
        self.assertIn("|title={{colorlink|#006cad|雄之助}}", text)
        self.assertIn("{{#ifeq:{{{1}}}|collapsed", text)
        self.assertIn("|titlestyle = background:#94ceda;color:#006cad", text)
        self.assertIn("|group1 = 投稿的<br>原创曲目", text)
        self.assertIn("|list1 = {{Navbox_subgroup", text)
        self.assertIn("|list1 = {{lj|{{links|时滞记录{{!}}{{lj|ラグタイムレコード}}}}}}", text)
        self.assertIn("|list2 = {{lj|{{links|Navy|天堂中文{{!}}{{lj|天堂}}}}}}", text)
        self.assertIn("|group3 = 其他", text)
        self.assertIn("|group2 = 专辑", text)
        self.assertIn("|list2 = {{lj|{{linksplit|c=#|prefix=雄之助|Void|Pathos}}}}", text)
        self.assertEqual(text.count("{{"), text.count("}}"))       # 花括号配平

    def test_build_template_without_albums_or_songs(self):
        work = pt.ProducerWork(artist=pt.ProducerArtist(id=1, name="某人"))
        text = pt.build_template(work)
        self.assertNotIn("专辑", text)
        self.assertNotIn("Navbox_subgroup", text)
        self.assertIn("|name=某人", text)
        self.assertEqual(text.count("{{"), text.count("}}"))

    def test_template_links(self):
        text = pt.build_template(self._work())
        self.assertEqual(pt.template_links(text),
                         ["时滞记录", "Navy", "天堂中文", "没日期"])
        self.assertNotIn("Void", pt.template_links(text))          # 专辑是 linksplit，不算条目


class InsertTemplateTest(unittest.TestCase):
    """插到哪儿 —— 三篇真实编辑（用户 2026-10 手改过的版本）当基准。

    之前写错了：把新模板放在 `== 注释 ==` **标题上方**，而站上（以及用户手改后的版本）是
    放在**小节里**、`<references/>` 后面；注释标题上方那一串大家族模板还要一并挪进小节。
    """

    def test_insert_into_the_note_section_after_references(self):
        text = "正文\n\n== 注释与外部链接 ==\n<references/>\n{{szri}}\n"
        new_text, note = pt.insert_template(text, "Ruliea")
        self.assertEqual(new_text,
                         "正文\n\n== 注释与外部链接 ==\n<references/>\n{{Ruliea}}\n{{szri}}\n")
        self.assertIn("<references/> 后面", note)

    def test_family_templates_above_the_heading_are_moved_down(self):
        """注释标题上方的大家族模板一并挪进小节，新模板插在「最靠近标题的那一行」上面。

        `{{clear}}` 这种排版模板不算大家族模板，留在原处。
        """
        text = ("正文\n\n{{-}}\n\n{{clear}}\n{{NurseRobot TypeT}}\n"
                "{{The VOCALOID Collection2025冬}}\n== 注释与外部链接 ==\n<references/>\n")
        new_text, note = pt.insert_template(text, "Ruliea")
        self.assertEqual(
            new_text,
            "正文\n\n{{-}}\n\n{{clear}}\n\n== 注释与外部链接 ==\n<references/>\n"
            "{{NurseRobot TypeT}}\n{{Ruliea}}\n{{The VOCALOID Collection2025冬}}\n")
        self.assertIn("2 个大家族模板", note)

    def test_note_section_without_references(self):
        text = "正文\n\n== 注释 ==\n{{P主|collapsed}}\n"
        new_text, note = pt.insert_template(text, "新P主")
        self.assertEqual(new_text, "正文\n\n== 注释 ==\n{{新P主}}\n{{P主|collapsed}}\n")
        self.assertIn("注释小节里", note)

    def test_insert_when_no_note_section(self):
        new_text, note = pt.insert_template("正文\n", "新P主")
        self.assertEqual(new_text, "正文\n\n{{新P主}}\n")
        self.assertIn("没有注释小节", note)

    def test_insert_without_note_section_goes_above_the_family_templates(self):
        """没有注释小节、末尾是大家族模板 + 分类行时，新模板插在**最靠近分类的那一行**上面。

        实测 虽然是人类。：用户手改后的版本（revid 251458）就是 `{{Ruliea}}` 在
        `{{The VOCALOID Collection2026夏}}` 之上；2026-09 之前插到了它下面（revid 251450）。
        """
        text = ("正文\n\n{{晴一番}}\n{{The VOCALOID Collection2024冬}}\n\n"
                "[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n")
        new_text, note = pt.insert_template(text, "雄之助")
        self.assertEqual(
            new_text,
            "正文\n\n{{晴一番}}\n{{雄之助}}\n{{The VOCALOID Collection2024冬}}\n\n"
            "[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n")
        self.assertIn("末尾大家族模板上方", note)
        # 末尾没有大家族模板时才插到分类行上方
        text = "正文\n\n[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n"
        new_text, note = pt.insert_template(text, "雄之助")
        self.assertEqual(new_text,
                         "正文\n\n{{雄之助}}\n\n[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n")
        self.assertIn("分类行上方", note)
        # 分类行夹在中间（后面还有正文）时不算「末尾的分类」，照旧追加到末尾
        text = "正文\n[[分类:甲]]\n还有正文\n"
        self.assertTrue(pt.insert_template(text, "雄之助")[0].endswith("{{雄之助}}\n"))

    def test_layout_templates_stay_put_without_a_note_section(self):
        """`{{clear}}` 这类排版模板不算大家族模板（与注释小节那一路一致）。"""
        text = "正文\n\n{{clear}}\n\n[[分类:日本音乐作品]]\n"
        new_text, note = pt.insert_template(text, "雄之助")
        self.assertEqual(new_text, "正文\n\n{{clear}}\n\n{{雄之助}}\n\n[[分类:日本音乐作品]]\n")
        self.assertIn("分类行上方", note)

    def test_skip_when_already_there(self):
        for text in ("正文\n{{雄之助}}\n== 注释 ==\n", "正文\n{{雄之助|collapsed}}\n== 注释 ==\n"):
            new_text, note = pt.insert_template(text, "雄之助")
            self.assertEqual(new_text, text)
            self.assertIn("已包含", note)

    def test_skip_when_already_there_with_prefix(self):
        text = "正文\n{{雄之助}}\n== 注释 ==\n"
        new_text, note = pt.insert_template(text, "Template:雄之助")
        self.assertEqual(new_text, text)

    def test_empty_inputs(self):
        self.assertEqual(pt.insert_template("", "X")[0], "")
        self.assertEqual(pt.insert_template("正文", "")[0], "正文")

    def test_note_heading_variants(self):
        for heading in ("== 注释 ==", "==注释==", "=== 注解 ===", "== 注释与外部链接 ==",
                        "== 参考 =="):
            text = f"正文\n\n{heading}\n<references/>\n"
            new_text, _ = pt.insert_template(text, "P主模板")
            self.assertEqual(new_text,
                             f"正文\n\n{heading}\n<references/>\n{{{{P主模板}}}}\n", heading)
        # 只有「外部链接」时不算注释小节 → 追加到末尾
        text = "正文\n\n== 外部链接 ==\n* x\n"
        new_text, note = pt.insert_template(text, "P主模板")
        self.assertTrue(new_text.endswith("{{P主模板}}\n"))

    def test_real_edits_replay_exactly(self):
        """与用户手改后的四篇（再见天才 / 曾想与你对称 / Last dinner / 虽然是人类。）逐字节一致。

        每篇的「原版」就是 User:人间百态 编辑之前的版本
        （revid 210953 / 221270 / 247542 / 248762），
        「正确版」是用户随后手改的版本（251453 / 251457 / 251451 / 251458）；这里是它们的正文尾部。

        实测 虽然是人类。 全篇回放也是内容逐字节一致（只差 MediaWiki 去掉的行尾那一个换行）：
        旧逻辑（插到分类行上方）写出来的就是用户报的 revid 251450。
        """
        cases = [
            # 再见天才：两个大家族模板在注释标题上方
            ("…\n}}\n{{NurseRobot TypeT}}\n{{The VOCALOID Collection2025冬}}\n"
             "== 注释与外部链接 ==\n<references/>\n[[分类:日本音乐作品]]\n",
             "…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{NurseRobot TypeT}}\n"
             "{{Ruliea}}\n{{The VOCALOID Collection2025冬}}\n\n[[分类:日本音乐作品]]\n"),
            # 曾想与你对称：注释小节里已经有一个大家族模板
            ("…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{szri}}\n"
             "{{NurseRobot_TypeT|collapsed}}\n[[分类:日本音乐作品]]\n",
             "…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{Ruliea}}\n{{szri}}\n"
             "{{NurseRobot_TypeT|collapsed}}\n\n[[分类:日本音乐作品]]\n"),
            # Last dinner：注释小节里有一个模板，且分类前本来就空了一行
            ("…\n}}\n\n== 注释与外部链接 ==\n<references/>\n"
             "{{The VOCALOID Collection2024冬}}\n\n[[分类:日本音乐作品]]\n",
             "…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{Ruliea}}\n"
             "{{The VOCALOID Collection2024冬}}\n\n[[分类:日本音乐作品]]\n"),
            # 虽然是人类。：**没有**注释小节，末尾是大家族模板 + 分类行
            ("…\n}}\n\n{{The VOCALOID Collection2026夏}}\n\n"
             "[[Category:日本音乐作品]]\n[[Category:初音未来歌曲]]\n",
             "…\n}}\n\n{{Ruliea}}\n{{The VOCALOID Collection2026夏}}\n\n"
             "[[Category:日本音乐作品]]\n[[Category:初音未来歌曲]]\n"),
        ]
        for original, expected in cases:
            new_text, _note = pt.insert_template(original, "Ruliea")
            self.assertEqual(new_text, expected)


class InsertIntoPagesTest(unittest.TestCase):
    def test_insert_into_pages(self):
        texts = {"时滞记录": "正文\n\n{{P主|collapsed}}\n== 注释 ==\n<references/>\n",
                 "Navy": "正文\n\n{{雄之助}}\n== 注释 ==\n"}
        edited = []
        seen = []
        with mock.patch.object(pt.wiki_api, "fetch_pages_text", return_value=texts), \
                mock.patch.object(pt.wiki_api, "edit_page",
                                  side_effect=lambda title, text, summary="": edited.append(title)
                                  or {"ok": True}):
            results = pt.insert_into_pages("雄之助", ["时滞记录", "Navy", "不存在"], seen.append)
        self.assertEqual([r["title"] for r in results], ["时滞记录", "Navy", "不存在"])
        self.assertTrue(results[0]["ok"])
        self.assertEqual(results[1]["count"], 0)                 # 已经有了
        self.assertFalse(results[2]["ok"])
        self.assertEqual(edited, ["时滞记录"])
        self.assertEqual(len(seen), 3)

    def test_insert_into_pages_reports_edit_failure(self):
        with mock.patch.object(pt.wiki_api, "fetch_pages_text",
                               return_value={"A": "正文\n== 注释 ==\n"}), \
                mock.patch.object(pt.wiki_api, "edit_page",
                                  return_value={"ok": False, "error": "被权限挡住"}):
            results = pt.insert_into_pages("P主", ["A"])
        self.assertFalse(results[0]["ok"])
        self.assertIn("权限", results[0]["error"])


if __name__ == "__main__":
    unittest.main()
