"""`utils/producer_template.py` 的单测：HTTP / 维基全部 mock，不联网。"""
import json
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from utils import producer_template as pt


class _Response:
    def __init__(self, payload, cookies=None):
        self.text = json.dumps(payload) if not isinstance(payload, str) else payload
        self.status_code = 200
        # b 站搜索要 cookie（`bilibili_cookies()` 从预热响应里读），所以这里也带一份
        self.cookies = dict(cookies or {})

    def raise_for_status(self):
        return None

    def json(self):
        return json.loads(self.text)


def _patch_get(routes):
    """按 url 前缀分发假响应；返回 mock 出来的 `http_get`。"""

    def fake_get(url, use_proxy=False, params=None, timeout=None, **kwargs):
        for prefix, payload in routes.items():
            if url.startswith(prefix):
                if callable(payload):
                    return _Response(payload(params or {}))
                return _Response(payload)
        raise AssertionError(f"没准备好这个地址的假响应：{url}")

    return mock.patch.object(pt, "http_get", side_effect=fake_get)


SONG_ITEM = {
    "id": 1, "defaultName": "天堂", "artistString": "雄之助 feat. 初音ミク",
    "publishDate": "2024-08-28T00:00:00Z", "songType": "Original",
}

# 站上 `偏执狂` 这个条目的真实样子（revid 251575）：全て奴等の所為です。 的《パラノイア》
# （2020）—— 和 shikisai 的同名曲撞了名字，用户 2026-09-29 用它报的重名问题。
OTHER_PARANOIA_PAGE = (
    "{{标题替换|パラノイア}}\n{{VOCALOID Songbox\n"
    "|image = paranoia_subeyatsu.jpg\n"
    "|颜色 = black;color:#FFF\n"
    "|演唱 = {{lj|[[デフォ子]]}}\n"
    "|歌曲名称 = {{lj|パラノイア}}<br>Paranoia<br>偏执狂\n"
    "|P主 = {{lj|[[全て奴等の所為です。]]}}\n"
    "|yt_id = wChevHfClbs\n"
    "|投稿时间 = 2020年8月11日\n}}\n"
)


class ParseHelpersTest(unittest.TestCase):
    def test_clean_title(self):
        self.assertEqual(pt.clean_title("{{lj|ループメモリー}}"), "ループメモリー")
        self.assertEqual(pt.clean_title("{{lj|[[时滞记录|ラグタイムレコード]]}}"), "ラグタイムレコード")
        self.assertEqual(pt.clean_title("[[中文|日文]]"), "日文")
        self.assertEqual(pt.clean_title("超新星{{!}}Supernova"), "超新星")
        self.assertEqual(pt.clean_title("<!--\n-->Navy<!--\n-->"), "Navy")
        self.assertEqual(pt.clean_title("'''粗体'''"), "粗体")

    def test_template_calls_handles_nesting(self):
        text = "{{lj|{{links|A{{!}}B|C}}}}"
        self.assertEqual(pt.template_calls(text, "links"), ["A{{!}}B|C"])

    def test_split_args_ignores_nested_pipes(self):
        self.assertEqual(pt.split_args("A{{!}}B|{{lj|C}}|D"), ["A{{!}}B", "{{lj|C}}", "D"])

    def test_parse_publish_date(self):
        self.assertEqual(pt.parse_publish_date("2026-08-28T00:00:00Z"), "2026-08-28")
        self.assertEqual(pt.parse_publish_date("2024-08"), "2024-08")
        self.assertEqual(pt.parse_publish_date("2024"), "2024")
        self.assertEqual(pt.parse_publish_date(None), "")
        self.assertEqual(pt.parse_publish_date("不是日期"), "")

    def test_parse_artist_id(self):
        self.assertEqual(pt.parse_artist_id("23981"), 23981)
        self.assertEqual(pt.parse_artist_id("https://vocadb.net/Artist/Details/23981"), 23981)
        self.assertEqual(pt.parse_artist_id("雄之助"), 0)


class AutoUploadTest(unittest.TestCase):
    """只有发行商代传的 YouTube 自动投稿的曲子不收（用户 2026-10 要求）。

    实测 S/950828（ワープループ）：唯一的 PV 是 `author = "Yunosuke - Topic"`、
    简介 `Provided to YouTube by NexTone Inc. … Auto-generated by YouTube.`。
    """

    TOPIC = {"service": "Youtube", "author": "Yunosuke - Topic",
             "description": "Provided to YouTube by NexTone Inc.\n\nワープループ\n\n"
                            "Auto-generated by YouTube."}
    REAL = {"service": "NicoNicoDouga", "author": "雄之助", "description": "新曲です"}

    def test_is_auto_upload(self):
        self.assertTrue(pt.is_auto_upload(self.TOPIC))
        self.assertTrue(pt.is_auto_upload({"author": "雄之助 - Topic"}))
        self.assertTrue(pt.is_auto_upload({"description": "Provided to YouTube by X"}))
        self.assertTrue(pt.is_auto_upload({"description": "Auto-generated by YouTube."}))
        self.assertFalse(pt.is_auto_upload(self.REAL))
        self.assertFalse(pt.is_auto_upload({}))

    def test_has_real_pv(self):
        self.assertFalse(pt.has_real_pv({"pvs": [self.TOPIC]}))
        self.assertTrue(pt.has_real_pv({"pvs": [self.TOPIC, self.REAL]}))   # 混着就保留
        self.assertTrue(pt.has_real_pv({"pvs": [self.REAL]}))
        self.assertTrue(pt.has_real_pv({}))                                   # 没信息就不删

    def test_fetch_songs_skips_auto_upload_only_songs(self):
        payload = {"items": [
            {**SONG_ITEM, "id": 1, "defaultName": "ワープループ", "pvs": [self.TOPIC]},
            {**SONG_ITEM, "id": 2, "defaultName": "ネハン",
             "pvs": [self.TOPIC, self.REAL]},
            {**SONG_ITEM, "id": 3, "defaultName": "没有 PV 信息"},
        ]}
        with _patch_get({pt.VOCADB_SONG_URL: payload}):
            songs = pt.fetch_songs(23981)
        self.assertEqual(["ネハン", "没有 PV 信息"], [song.ja for song in songs])


class ProducerOnlyTest(unittest.TestCase):
    """只留「制作人是他本人」的曲目（用户 2026-09 要求）。

    先定的规则是「职位是 Other 和演奏者的不收」，后来又收窄成
    「将所有的参与曲目从模板中删除，只保留制作人为 P主本人的条目」——
    现在只看署名里有没有 `Default`（VocaDB 的主艺人）或 `Composer`（作曲）：
    实测 Ruliea《セプテントリオー》他是 `Mastering`、《絶滅によろしく》是 `Other`，
    読谷あかね《ポリへドロン》《頭ン痛》是 `Animator` / `Illustrator` —— 都不收。
    """

    ARTIST = 123110

    def _item(self, roles, **extra):
        return {"defaultName": "曲", "publishDate": "2025-01-01T00:00:00Z",
                "pvs": [{"service": "NicoNicoDouga", "author": "别人",
                         "publishDate": "2025-01-01T00:00:00"}],
                "artists": [{"id": self.ARTIST, "roles": roles, **extra}]}

    def test_credit_roles_splits_and_lowercases(self):
        self.assertEqual({"instrumentalist", "mastering"},
                         pt.credit_roles({"roles": "Instrumentalist, Mastering"}))
        self.assertEqual({"other"}, pt.credit_roles({"effectiveRoles": "Other"}))
        self.assertEqual(set(), pt.credit_roles({}))

    def test_only_the_producer_counts(self):
        for roles in ("Default", "Composer", "default, mastering",
                      "Animator, Illustrator, Composer", "Default, Animator"):
            self.assertTrue(pt.is_own_song(self._item(roles), self.ARTIST), roles)

    def test_participation_roles_are_not_his_song(self):
        # 母带 / 演奏 / 动画 / 曲绘 / 写词 / 编曲 / 挂名 —— 全是别人的曲子
        for roles in ("Mastering", "Instrumentalist", "Other", "Animator", "Illustrator",
                      "Lyricist", "Arranger", "Instrumentalist, Mastering",
                      "other, instrumentalist", "Animator, Illustrator", "Mixer", "Vocalist"):
            self.assertFalse(pt.is_own_song(self._item(roles), self.ARTIST), roles)

    def test_missing_data_keeps_the_song(self):
        self.assertTrue(pt.is_own_song({}, self.ARTIST))                       # 没 artists
        self.assertTrue(pt.is_own_song({"artists": []}, self.ARTIST))
        self.assertTrue(pt.is_own_song({"artists": [{"id": 999, "roles": "Other"}]},
                                       self.ARTIST))                            # 署名里没他
        mixed = {"artists": [{"id": 999, "roles": "Other"},
                             {"id": self.ARTIST, "roles": "Mastering"}]}
        self.assertFalse(pt.is_own_song(mixed, self.ARTIST))                   # 他只有参与署名

    def test_artist_id_can_be_nested(self):
        item = {"artists": [{"artist": {"id": self.ARTIST}, "roles": "Mastering"}]}
        self.assertFalse(pt.is_own_song(item, self.ARTIST))
        mine = {"artists": [{"artist": {"id": self.ARTIST}, "roles": "Default"}]}
        self.assertTrue(pt.is_own_song(mine, self.ARTIST))

    def test_fetch_songs_skips_participation_songs(self):
        payload = {"items": [self._item("Mastering"), self._item("Default"),
                             self._item("Animator, Illustrator")]}
        payload["items"][0]["defaultName"] = "セプテントリオー"
        payload["items"][1]["defaultName"] = "憑いている"
        payload["items"][2]["defaultName"] = "他只做了 PV"
        with _patch_get({pt.VOCADB_SONG_URL: payload}) as get:
            songs = pt.fetch_songs(self.ARTIST)
        self.assertEqual(["憑いている"], [song.ja for song in songs])
        # 要拿署名就得带上 `Artists` 字段
        self.assertIn("Artists", get.call_args.kwargs["params"]["fields"])


class OwnAlbumTest(unittest.TestCase):
    """合辑 / 多艺人发行 / 只是挂名支持的专辑不收（用户 2026-10 要求）。"""

    def test_various_artists_is_not_ours(self):
        # Al/55475「音速を超えて」、Al/54757「NIGHT HIKE Compilation Vol.1」
        for name in ("音速を超えて", "NIGHT HIKE Compilation Vol.1"):
            self.assertFalse(pt.is_own_album(
                {"name": name, "artistString": "Various artists", "artists": [
                    {"artist": {"id": 23981}, "isSupport": False, "roles": "Default"}]},
                23981))

    def test_support_only_credits_are_not_ours(self):
        self.assertFalse(pt.is_own_album(
            {"name": "hologram", "artistString": "Ruliea feat. various", "artists": [
                {"artist": {"id": 123110}, "isSupport": False, "roles": "Default"},
                {"artist": {"id": 23981}, "isSupport": True, "roles": "Arranger"}]},
            23981))

    def test_own_albums_are_kept(self):
        self.assertTrue(pt.is_own_album(
            {"name": "Void", "artistString": "雄之助 feat. various", "artists": [
                {"artist": {"id": 23981}, "isSupport": False, "roles": "Default"}]},
            23981))
        # 没有 artistString / artists 时一律保留（宁可多留，不要误删）
        self.assertTrue(pt.is_own_album({"name": "Void"}, 23981))
        # 艺人列表里没有他 → 也不能因此当作「只是挂名」
        self.assertTrue(pt.is_own_album(
            {"name": "Void", "artistString": "Yunosuke",
             "artists": [{"artist": {"id": 999}, "isSupport": False}]}, 23981))

    def test_fetch_albums_filters_and_dedupes(self):
        payload = {"items": [
            {"name": "Void", "releaseDate": {"year": 2025},
             "artistString": "雄之助 feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "音速を超えて", "releaseDate": {"year": 2026},
             "artistString": "Various artists",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "hologram", "releaseDate": {"year": 2024},
             "artistString": "Ruliea feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": True}]},
            {"name": "Pathos", "releaseDate": {"year": 2016},
             "artistString": "雄之助, 攻 feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "Void", "releaseDate": {"year": 2025},
             "artistString": "雄之助 feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "", "releaseDate": {"year": 2020}},
        ]}
        with _patch_get({pt.VOCADB_ALBUM_URL: payload}) as get:
            albums = pt.fetch_albums(23981)
        self.assertEqual(["Pathos", "Void"], albums)
        self.assertEqual("Album", get.call_args.kwargs["params"]["discTypes"])
        self.assertEqual(23981, get.call_args.kwargs["params"]["artistId[]"])
        self.assertIn("Artists", get.call_args.kwargs["params"]["fields"])


class AvatarTest(unittest.TestCase):
    """P主头像（`utils/producer_template.py`）：当「样式」页的默认参考图。

    用户 2026-10 要求「选择参考图默认选择 P主头像下载并交给 AI 生成 CSS」。
    """

    URL = "https://static.vocadb.net/img/Artist/mainOrig/23981.jpg?v=37"

    def _artist(self, picture: str = URL) -> pt.ProducerArtist:
        return pt.ProducerArtist(id=23981, name="雄之助", artist_type="Producer",
                                 picture=picture)

    def test_to_artist_reads_the_main_picture(self):
        artist = pt._to_artist({"id": 23981, "name": "雄之助", "artistType": "Producer",
                                "mainPicture": {"urlOriginal": self.URL,
                                                "urlThumb": "https://x/thumb.jpg"}})
        self.assertEqual(self.URL, artist.picture)
        # 只有缩略图时退到缩略图
        thumb = pt._to_artist({"id": 1, "name": "A",
                               "mainPicture": {"urlTinyThumb": "https://x/tiny.jpg"}})
        self.assertEqual("https://x/tiny.jpg", thumb.picture)
        self.assertEqual("", pt._to_artist({"id": 1, "name": "A"}).picture)
        self.assertEqual("", pt._to_artist({"id": 1, "name": "A", "mainPicture": None}).picture)

    def test_artist_requests_the_main_picture_field(self):
        """实测：不传 `fields=MainPicture` 时响应里只有 `pictureMime`，没有地址。"""
        payload = {"id": 23981, "name": "雄之助"}
        with _patch_get({f"{pt.VOCADB_ARTIST_URL}/23981": payload}) as get:
            pt.fetch_artist(23981)
        self.assertEqual(pt.ARTIST_FIELDS, get.call_args.kwargs["params"]["fields"])
        with _patch_get({pt.VOCADB_ARTIST_URL: {"items": [payload]}}) as get:
            pt.search_artists("雄之助")
        self.assertEqual(pt.ARTIST_FIELDS, get.call_args.kwargs["params"]["fields"])

    def test_avatar_filename(self):
        self.assertEqual("P主头像_雄之助.jpg", pt.avatar_filename(self._artist()))
        # 地址里没有扩展名 / 没有头像时退回 .jpg（AI 那边按后缀判 mime）
        self.assertEqual("P主头像_雄之助.jpg",
                         pt.avatar_filename(self._artist("https://x/mainOrig/23981")))
        self.assertEqual("P主头像_雄之助.jpg", pt.avatar_filename(self._artist("")))
        self.assertEqual("P主头像_雄之助.jpg",
                         pt.avatar_filename(pt.ProducerArtist(id=1, name="雄之助")))

    def test_download_avatar_writes_into_the_output_folder(self):
        with tempfile.TemporaryDirectory() as folder:
            def fake_download(url, target):
                Path(target).write_bytes(b"x" * 32)
                return True

            with mock.patch.object(pt.image, "download_file",
                                   side_effect=fake_download) as download:
                path = pt.download_avatar(self._artist(), folder)
            target = Path(folder) / "P主头像_雄之助.jpg"
            self.assertEqual(target, path)
            self.assertTrue(path.is_file())
            download.assert_called_once_with(self.URL, target)
            # 已经下过就直接用现成的，不重复下载
            with mock.patch.object(pt.image, "download_file") as again:
                self.assertEqual(target, pt.download_avatar(self._artist(), folder))
            again.assert_not_called()

    def test_download_avatar_without_a_picture(self):
        with mock.patch.object(pt.image, "download_file") as download:
            self.assertIsNone(pt.download_avatar(self._artist(""), tempfile.mkdtemp()))
            self.assertIsNone(pt.download_avatar(pt.ProducerArtist(id=1, name="A")))
        download.assert_not_called()

    def test_download_avatar_swallows_errors(self):
        with tempfile.TemporaryDirectory() as folder, \
                mock.patch.object(pt.image, "download_file", side_effect=RuntimeError("boom")):
            self.assertIsNone(pt.download_avatar(self._artist(), folder))


class VocaDbTest(unittest.TestCase):
    def test_search_artists_by_name(self):
        payload = {"items": [{"id": 23981, "name": "雄之助", "artistType": "Producer",
                              "additionalNames": "Yunosuke"}]}
        with _patch_get({pt.VOCADB_ARTIST_URL: payload}) as get:
            artists = pt.search_artists("雄之助")
        self.assertEqual(len(artists), 1)
        self.assertEqual(artists[0].id, 23981)
        self.assertEqual(artists[0].name_en, "Yunosuke")
        # 名字搜索走 query，不该带 artistId
        self.assertEqual(get.call_args.kwargs["params"]["query"], "雄之助")

    def test_search_artists_by_url_goes_to_details(self):
        payload = {"id": 23981, "name": "雄之助", "artistType": "Producer"}
        with _patch_get({f"{pt.VOCADB_ARTIST_URL}/23981": payload}) as get:
            artists = pt.search_artists("https://vocadb.net/Artist/Details/23981")
        self.assertEqual(artists[0].name, "雄之助")
        self.assertTrue(get.call_args.args[0].endswith("/artists/23981"))

    def test_search_artists_empty_query(self):
        self.assertEqual(pt.search_artists("  "), [])

    def test_fetch_songs_uses_array_param_and_sorts(self):
        pages = {}

        def handler(params):
            pages["params"] = params
            return {"items": [SONG_ITEM,
                              {**SONG_ITEM, "id": 2, "defaultName": "早安",
                               "publishDate": "2020-01-01T00:00:00Z"}]}

        with _patch_get({pt.VOCADB_SONG_URL: handler}):
            songs = pt.fetch_songs(23981)
        self.assertEqual([s.ja for s in songs], ["早安", "天堂"])       # 按日期从早到晚
        self.assertEqual(pages["params"]["artistId[]"], 23981)
        self.assertEqual(pages["params"]["songTypes"], "Original")
        self.assertEqual(pages["params"]["onlyWithPvs"], "true")
        self.assertNotIn("artistId", pages["params"])                # 写成 artistId 会被静默忽略

    def test_fetch_songs_dedupes_and_pages(self):
        calls = []

        def handler(params):
            calls.append(params["start"])
            if params["start"] == 0:
                return {"items": [SONG_ITEM] * 100}
            return {"items": [{**SONG_ITEM, "id": 3, "defaultName": "再来",
                               "publishDate": "2026-01-01T00:00:00Z"}]}

        with _patch_get({pt.VOCADB_SONG_URL: handler}):
            songs = pt.fetch_songs(23981)
        self.assertEqual(calls, [0, 100])
        self.assertEqual([s.ja for s in songs], ["天堂", "再来"])

    def test_fetch_works_without_artist(self):
        with _patch_get({pt.VOCADB_ARTIST_URL: {"items": []}}):
            work = pt.fetch_works("不存在的人")
        self.assertEqual(work.songs, [])
        self.assertEqual(work.artist.name, "")

    def test_pv_date_takes_the_earliest_official_upload(self):
        """用户 2026-09 要求：排序看**稿件**的投稿日期，不看 VocaDB 的发行日期。

        实测 Ruliea《エキセントリックブルー》：VocaDB `publishDate = 2024-01-15`（专辑发行日），
        而 Nico / YouTube 上的稿件是 2024-12-20 —— 以前就按 2024-01-15 排在年初了。
        """
        item = {"pvs": [
            {"service": "NicoNicoDouga", "author": "Ruliea", "publishDate": "2024-12-20T00:00:00"},
            {"service": "Youtube", "author": "Ruliea", "publishDate": "2024-12-20T00:00:00"},
            {"service": "Youtube", "author": "Ruliea - Topic", "publishDate": "2023-01-01T00:00:00"},
        ]}
        self.assertEqual("2024-12-20", pt.pv_date(item))
        # 只有自动投稿（发行商代传）→ 不能当投稿日期
        auto_only = {"pvs": [{"service": "Youtube", "author": "Ruliea - Topic",
                              "publishDate": "2026-05-08T00:00:00"}]}
        self.assertEqual("", pt.pv_date(auto_only))
        self.assertEqual("", pt.pv_date({}))
        self.assertEqual("", pt.pv_date({"pvs": [{"author": "Ruliea"}]}))

    def test_song_from_vocadb_falls_back_to_publish_date(self):
        """一个能用的 PV 日期都没有（没 PV 信息）才退回 `publishDate`。"""
        self.assertEqual("2024-01-15",
                         pt.song_from_vocadb({"defaultName": "A",
                                              "publishDate": "2024-01-15T00:00:00Z"}).date)
        item = {"defaultName": "B", "publishDate": "2024-01-15T00:00:00Z",
                "pvs": [{"service": "NicoNicoDouga", "author": "B",
                          "publishDate": "2024-12-20T00:00:00"}]}
        self.assertEqual("2024-12-20", pt.song_from_vocadb(item).date)

    def test_fetch_songs_sorts_by_pv_date(self):
        """投稿日期决定年份格与先后顺序（专辑发行日不管用）。"""
        early_album = {"id": 1, "defaultName": "专辑里先发的",
                       "publishDate": "2024-01-15T00:00:00Z",
                       "pvs": [{"service": "NicoNicoDouga", "author": "P",
                                "publishDate": "2025-03-01T00:00:00"}]}
        later_album = {"id": 2, "defaultName": "后来单独发的",
                       "publishDate": "2024-06-01T00:00:00Z",
                       "pvs": [{"service": "NicoNicoDouga", "author": "P",
                                "publishDate": "2024-06-02T00:00:00"}]}
        with _patch_get({pt.VOCADB_SONG_URL: {"items": [early_album, later_album]}}):
            songs = pt.fetch_songs(1)
        self.assertEqual([s.ja for s in songs], ["后来单独发的", "专辑里先发的"])
        self.assertEqual([s.date for s in songs], ["2024-06-02", "2025-03-01"])
        groups = pt.build_song_groups(songs)
        self.assertEqual([label for label, _ in groups], ["2024", "2025"])


class ProducerPageTest(unittest.TestCase):
    PAGE = """== 歌曲 ==
{{Producer_Song
|nnd_id   = sm45871877
|作曲     = {{lj|はるまきごはん}}
|投稿日期 = 2025年8月21日
|条目     = 揉揉头
|标题     = {{lj|アタマモミ}}
|image    = x.jpg
}}

{{Producer_Song
|条目     = 时滞记录
|标题     = {{lj|[[时滞记录|ラグタイムレコード]]}}
}}

* 专辑：《[[#Void|Void]]》与 [[#Pathos|Pathos]]
{{lj|[[银河录|{{lj|銀河録}}]]}}
"""

    # 歌曲条目一定带信息框（实测：VOCALOID Songbox / VOCALOID_Songbox）
    SONG_PAGE = "{{VOCALOID Songbox\n|标题 = ラグタイムレコード\n}}\n'''ラグタイムレコード''' 即时滞记录。"
    # 榜单页：正文写着歌名，但没有信息框 —— 不是歌曲条目（实测第 87 期用的就是 {{Billboard}}）
    RANKING_PAGE = ("{{Billboard|index=87}}\n{| class=\"wikitable\"\n|-\n"
                    "| 1 || [[ラグタイムレコード]] || はるまきごはん\n|}")

    def test_parse_producer_page(self):
        mapping = pt.parse_producer_page(self.PAGE)
        self.assertEqual(mapping["アタマモミ"], "揉揉头")
        self.assertEqual(mapping["ラグタイムレコード"], "时滞记录")
        self.assertEqual(mapping["銀河録"], "银河录")
        self.assertNotIn("Void", mapping)          # `[[#Void|Void]]` 是专辑小节，不是条目
        self.assertNotIn("Pathos", mapping)

    def test_apply_wiki_names(self):
        songs = [pt.ProducerSong(ja="アタマモミ"), pt.ProducerSong(ja="未知的歌"),
                 pt.ProducerSong(ja="アタマモミ", cn="已填的")]
        filled = pt.apply_wiki_names(songs, {"アタマモミ": "揉揉头"})
        self.assertEqual(filled, 1)
        self.assertEqual(songs[0].cn, "揉揉头")
        self.assertEqual(songs[2].cn, "已填的")     # 已经填过的不覆盖

    def test_merge_page_songs_adds_wiki_only_songs(self):
        work = pt.ProducerWork(songs=[pt.ProducerSong(ja="アタマモミ", date="2025-08-21")])
        pt._merge_page_songs(work, self.PAGE)
        names = [s.ja for s in work.songs]
        self.assertIn("ラグタイムレコード", names)          # 页面上有、VocaDB 没给
        self.assertEqual(names.count("アタマモミ"), 1)      # 重复的不再加一遍
        added = [s for s in work.songs if s.ja == "ラグタイムレコード"][0]
        self.assertEqual(added.source, "wiki")

    def test_mark_existing_fills_chinese_name(self):
        songs = [pt.ProducerSong(ja="ラグタイムレコード"), pt.ProducerSong(ja="不存在")]
        pt.mark_existing(songs, {"时滞记录": "正文"})
        self.assertFalse(songs[0].page_exists)
        pt.mark_existing([pt.ProducerSong(ja="タイトル")], {"タイトル": "正文"})
        songs = [pt.ProducerSong(ja="ラグタイムレコード", cn="时滞记录")]
        pt.mark_existing(songs, {"时滞记录": "正文"})
        self.assertTrue(songs[0].page_exists)

    def test_resolve_from_wiki(self):
        work = pt.ProducerWork(artist=pt.ProducerArtist(id=1, name="雄之助"),
                               songs=[pt.ProducerSong(ja="ラグタイムレコード"),
                                      pt.ProducerSong(ja="Navy")])
        texts = {"雄之助": self.PAGE, "时滞记录": "正文", "Navy": "正文"}
        with mock.patch.object(pt.wiki_api, "fetch_pages_text",
                               side_effect=lambda titles: {t: texts[t] for t in titles
                                                           if t in texts}), \
                mock.patch.object(pt.wiki_api, "redirect_targets", return_value={}):
            pt.resolve_from_wiki(work)
        self.assertEqual(work.page_name, "雄之助")
        by_ja = {song.ja: song for song in work.songs}
        self.assertEqual(by_ja["ラグタイムレコード"].cn, "时滞记录")
        self.assertEqual(by_ja["アタマモミ"].cn, "揉揉头")          # 从 P主条目里补进来的
        self.assertEqual(by_ja["アタマモミ"].date, "2025-08-21")   # 日期也来自 {{Producer_Song}}

    def test_has_name_wants_a_whole_name(self):
        """用户 2026-09 报的：`ぽい` 不该在 `神っぽいな` 上匹配、`マニュア` 不该匹配 `わたしマニュアル`。"""
        self.assertFalse(pt.has_name("神っぽいな", "ぽい"))
        self.assertFalse(pt.has_name("わたしマニュアル", "マニュア"))
        self.assertFalse(pt.has_name("それっぽい", "ぽい"))
        self.assertTrue(pt.has_name("神っぽいな", "神っぽいな"))          # 整串相等当然算
        self.assertTrue(pt.has_name("ぽい (feat. 初音ミク)", "ぽい"))      # 后面跟空格 / 括号
        self.assertTrue(pt.has_name("蓝果実/エオ", "エオ"))              # 斜杠隔开
        self.assertFalse(pt.has_name("", "ぽい"))
        self.assertFalse(pt.has_name("ぽい", ""))

    def test_declared_song_names_only_reads_the_title_and_the_songbox(self):
        """歌名只认 `{{标题替换|…}}` 与信息框里的那几个参数（`|标题 =` 别处到处都是）。"""
        text = ("{{其他版本|标题=别的歌}}\n"
                "{{VOCALOID Songbox\n|标题 = ラグタイムレコード\n|歌曲名称 = {{lj|ラグタイムレコード}}<br>时滞记录\n}}\n"
                "{{导航标题|2025}}`")
        self.assertEqual(["ラグタイムレコード", "时滞记录"], pt.declared_song_names(text))
        self.assertEqual(["散り散り"],
                         pt.declared_song_names("{{标题替换|{{lj|散り散り}}}}\n{{VOCALOID Songbox}}"))
        self.assertEqual(["神っぽいな", "像神一样呐"],
                         pt.declared_song_names("{{标题替换|{{lj|神っぽいな}}}}\n"
                                                "{{VOCALOID Songbox\n"
                                                "|歌曲名称 = {{lj|神っぽいな}}<br>像神一样呐\n}}"))
    def test_search_page_by_song_needs_the_page_to_own_that_name(self):
        """用户 2026-09 报的：搜「ぽい」不能拿《神っぽいな》的条目当答案。

        实测的四个误判（都是「正文里恰好出现过这几个字」）：搜 ぽい → 像神一样呐、
        搜 マニュア → 自我手册（其实是 `わたしマニュアル`）、搜 エオ → 青果实
        （P主 叫 `EO(エオ)`）、搜 頭ン痛 → 劈叉舞（其实是 `スプリットダンス`）。
        条目**自己声明**的歌名不是它，就不认。
        """
        pages = [
            ("像神一样呐", "{{标题替换|{{lj|神っぽいな}}}}\n{{VOCALOID Songbox\n"
                           "|歌曲名称 = {{lj|神っぽいな}}<br>像神一样呐\n}}"),
            ("自我手册", "{{标题替换|{{lj|わたしマニュアル}}}}\n{{VOCALOID Songbox\n"
                          "|歌曲名称 = {{lj|わたしマニュアル}}<br/>自我手册\n}}"),
            ("青果实", "{{标题替换|{{lj|青果実}}}}\n{{VOCALOID Songbox\n|P主 = {{lj|[[EO(エオ)]]}}\n}}"),
            ("劈叉舞", "{{标题替换|{{lj|スプリットダンス}}}}\n{{VOCALOID Songbox\n"
                       "|歌曲名称 = {{lj|スプリットダンス}}<br>Split Dance<br>劈叉舞、绝望之舞\n}}"),
        ]
        for ja, _title in (("ぽい", "像神一样呐"), ("マニュア", "自我手册"),
                           ("エオ", "青果实"), ("頭ン痛", "劈叉舞")):
            with mock.patch.object(pt.wiki_api, "search_pages_with_text", return_value=pages):
                self.assertEqual("", pt.search_page_by_song(pt.ProducerSong(ja=ja)), ja)
        # 真的是它的话照旧认（`四散` = 散り散り、`时滞记录` 用信息框的 `|标题 =`）
        good = [("四散", "{{标题替换|{{lj|散り散り}}}}\n{{VOCALOID Songbox\n"
                        "|歌曲名称 = {{lj|散り散り}}<br>四散\n}}"),
                ("时滞记录", self.SONG_PAGE)]
        with mock.patch.object(pt.wiki_api, "search_pages_with_text", return_value=good):
            self.assertEqual("四散", pt.search_page_by_song(pt.ProducerSong(ja="散り散り")))
            self.assertEqual("时滞记录",
                             pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")))
        # 页面标题就是日文原名 → 直接算
        with mock.patch.object(pt.wiki_api, "search_pages_with_text",
                               return_value=[("じゃんぱ", "{{VOCALOID Songbox}}")]):
            self.assertEqual("じゃんぱ", pt.search_page_by_song(pt.ProducerSong(ja="じゃんぱ")))

    def test_search_page_by_song_disambiguates_a_same_named_song_by_someone_else(self):
        """同名但是**别人的**歌 → 不链过去，改写站上的消歧义写法 `偏执狂(shikisai)`。

        用户 2026-09-29 拿 `Template:Shikisai` 与条目 `偏执狂` 的差异报的：站上《パラノイア》
        有两首 —— shikisai 的（2022）与 全て奴等の所為です。 的（2020，条目就叫 `偏执狂`），
        两首条目自认的歌名都是 `パラノイア`，光看歌名分不出来，只能比对信息框里的 `|P主 =`。
        工具当时把 shikisai 的那首链到了 `偏执狂`（还往那个条目里写了 `{{shikisai}}`），
        用户随后销掉了那笔编辑、把模板改成 `偏执狂(shikisai)`。
        """
        other = ("偏执狂", OTHER_PARANOIA_PAGE)
        with mock.patch.object(pt.wiki_api, "search_pages_with_text", return_value=[other]):
            self.assertEqual("偏执狂(shikisai)",
                             pt.search_page_by_song(pt.ProducerSong(ja="パラノイア"),
                                                    ["shikisai"]))
            # P主 对得上 → 就是这首歌，照旧用本名
            self.assertEqual("偏执狂",
                             pt.search_page_by_song(pt.ProducerSong(ja="パラノイア"),
                                                    ["全て奴等の所為です。"]))
            # 不传 P主 名时分不出来，只能照旧（这是旧行为，留着以免无声改变）
            self.assertEqual("偏执狂", pt.search_page_by_song(pt.ProducerSong(ja="パラノイア")))
        # 同名的别人的页排在前面、我们自己的页排在后 → 还是用我们的
        mine = ("パラノイア", "{{标题替换|パラノイア}}\n{{VOCALOID Songbox\n"
                            "|歌曲名称 = {{lj|パラノイア}}\n|P主 = [[shikisai]]\n}}")
        with mock.patch.object(pt.wiki_api, "search_pages_with_text",
                               return_value=[other, mine]):
            self.assertEqual("パラノイア",
                             pt.search_page_by_song(pt.ProducerSong(ja="パラノイア"),
                                                    ["shikisai"]))

    def test_page_by_other_producer_reads_the_p_mark_field(self):
        self.assertTrue(pt.page_by_other_producer(OTHER_PARANOIA_PAGE, "shikisai"))
        self.assertTrue(pt.page_by_other_producer(OTHER_PARANOIA_PAGE, ["Yomitan Akane"]))
        self.assertFalse(pt.page_by_other_producer(OTHER_PARANOIA_PAGE, "全て奴等の所為です。"))
        # 信息框里写 `[[Yomitan_Akane|{{lj|読谷あかね}}]]`（下划线 + 显示名）也要认得出
        underscore = ("{{VOCALOID Songbox\n|歌曲名称 = {{lj|ぐぬぬ}}\n"
                      "|P主 = [[Yomitan_Akane|{{lj|読谷あかね}}]]\n}}")
        self.assertFalse(pt.page_by_other_producer(underscore, ["Yomitan Akane"]))
        self.assertFalse(pt.page_by_other_producer(underscore, ["読谷あかね"]))
        self.assertTrue(pt.page_by_other_producer(underscore, ["shikisai"]))
        # 读不到 `|P主` 就不敢乱判（返回 False = 照旧用这个名字）
        self.assertFalse(pt.page_by_other_producer("{{VOCALOID Songbox\n|歌曲名称 = X\n}}",
                                                   "shikisai"))
        self.assertFalse(pt.page_by_other_producer("正文", "shikisai"))

    def test_disambiguated(self):
        self.assertEqual("偏执狂(shikisai)", pt.disambiguated("偏执狂", "shikisai"))
        self.assertEqual("偏执狂(shikisai)", pt.disambiguated("偏执狂(旧的)", "shikisai"))
        self.assertEqual("偏执狂", pt.disambiguated("偏执狂", ""))
        self.assertTrue(pt.is_disambiguated("偏执狂(shikisai)", "shikisai"))
        self.assertFalse(pt.is_disambiguated("偏执狂", "shikisai"))
        self.assertFalse(pt.is_disambiguated("偏执狂(shikisai)", ""))

    def test_work_producer_names_starts_with_the_page_name(self):
        work = pt.ProducerWork()
        work.page_name = "Yomitan Akane"
        work.template_name = "Yomitan Akane"
        work.artist = pt.ProducerArtist(id=120604, name="読谷あかね")
        self.assertEqual(["Yomitan Akane", "読谷あかね"], pt.work_producer_names(work))

    def test_canonicalise_names_uses_redirect_targets(self):
        """用户 2026-09 报的：`|条目 = Chilly` 实际是条重定向，真条目叫「四散」。"""
        songs = [pt.ProducerSong(ja="散り散り", cn="Chilly"),   # P主 页面里填的名字
                 pt.ProducerSong(ja="散り散り"),                # 日文原名本身就是重定向
                 pt.ProducerSong(ja="じゃんぱ")]                 # 不是重定向 → 不动
        with mock.patch.object(pt.wiki_api, "redirect_targets",
                               return_value={"Chilly": "四散", "散り散り": "四散"}):
            changed = pt.canonicalise_names(songs)
        self.assertEqual(2, changed)
        self.assertEqual("四散", songs[0].cn)
        self.assertEqual("四散", songs[1].cn)
        self.assertTrue(songs[1].page_exists)
        self.assertEqual("", songs[2].cn)
        # 查不到重定向（断网 / 站上没这条）→ 原样返回
        with mock.patch.object(pt.wiki_api, "redirect_targets", return_value={}):
            self.assertEqual(0, pt.canonicalise_names([pt.ProducerSong(ja="A", cn="B")]))
        with mock.patch.object(pt.wiki_api, "redirect_targets", side_effect=RuntimeError("boo")):
            self.assertEqual(0, pt.canonicalise_names([pt.ProducerSong(ja="A", cn="B")]))

    def test_search_page_by_song_prefers_page_with_japanese_name(self):
        result = [("雄之助", "别的"), ("时滞记录", self.SONG_PAGE)]
        with mock.patch.object(pt.wiki_api, "search_pages_with_text",
                               return_value=result):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")),
                             "时滞记录")
        with mock.patch.object(pt.wiki_api, "search_pages_with_text", return_value=[]):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")), "")

    def test_looks_like_song_page_needs_a_songbox(self):
        """歌曲条目都带 `{{…Songbox}}`；榜单页 / 专辑页 / P主页面 / 消歧义页都不带。"""
        self.assertTrue(pt.looks_like_song_page(self.SONG_PAGE))
        self.assertTrue(pt.looks_like_song_page("{{VOCALOID_Songbox\n|标题 = 时滞记录\n}}"))
        self.assertTrue(pt.looks_like_song_page("{{VOCALOID songbox}}"))     # 不区分大小写
        self.assertFalse(pt.looks_like_song_page(self.RANKING_PAGE))
        self.assertFalse(pt.looks_like_song_page("{{Album Infobox}}"))
        self.assertFalse(pt.looks_like_song_page("{{disambig}}"))
        self.assertFalse(pt.looks_like_song_page("{{Producer_Song|条目=随便}}"))
        self.assertFalse(pt.looks_like_song_page(""))
        self.assertFalse(pt.looks_like_song_page(None))

    def test_search_page_by_song_skips_pages_without_songbox(self):
        """用户 2026-10 报「中文名会变成 NICONICO VOCALOID SONGS TOP20/第87期」。

        实测那一页是 Billboard 榜单（用 `{{Billboard}}`），**正文里确实写着歌名**、
        可它没有 Songbox，不是歌曲条目 —— 以前只核对「正文提没提到日文名」，
        就把榜单页的标题当成中文条目名填进去了，模板最后还链到了榜单上。
        """
        ranking = ("NICONICO VOCALOID SONGS TOP20/第87期", self.RANKING_PAGE)
        with mock.patch.object(pt.wiki_api, "search_pages_with_text",
                               return_value=[ranking, ("时滞记录", self.SONG_PAGE)]):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")),
                             "时滞记录")
        with mock.patch.object(pt.wiki_api, "search_pages_with_text",
                               return_value=[ranking]):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")), "")

    def test_fill_missing_names(self):
        songs = [pt.ProducerSong(ja="已填", cn="已填"), pt.ProducerSong(ja="要找"),
                 pt.ProducerSong(ja="找不到")]
        seen = []
        with mock.patch.object(pt, "search_page_by_song",
                               side_effect=lambda song, *rest: "找到的页" if song.ja == "要找" else ""):
            filled = pt.fill_missing_names(songs, ["雄之助"], progress=seen.append)
        self.assertEqual(filled, 1)
        self.assertEqual(songs[1].cn, "找到的页")
        self.assertTrue(songs[1].page_exists)
        self.assertTrue(any("要找" in line for line in seen))

    def test_fill_missing_names_marks_a_disambiguated_name_as_missing(self):
        """消歧义名（`偏执狂(shikisai)`）站上还没页面 → `page_exists` 得记 False。"""
        songs = [pt.ProducerSong(ja="パラノイア")]
        with mock.patch.object(pt, "search_page_by_song",
                               return_value="偏执狂(shikisai)"):
            pt.fill_missing_names(songs, ["shikisai"])
        self.assertEqual("偏执狂(shikisai)", songs[0].cn)
        self.assertFalse(songs[0].page_exists)


class ExternalNameTest(unittest.TestCase):
    """外部来源搜中文名（`bilibili` / 网易云）：解析、来源可信度、维基核实、批量填充。

    用户 2026-10 要求「曲目」页能「从外部链接获取中文名」。
    """

    def setUp(self):
        # b 站 cookie 是模块级缓存：每条用例都从「没预热过」开始
        patcher = mock.patch.object(pt, "_bili_cookies", None)
        patcher.start()
        self.addCleanup(patcher.stop)

    def test_is_chinese_name(self):
        self.assertTrue(pt.is_chinese_name("时滞记录"))
        self.assertTrue(pt.is_chinese_name("揉揉头"))
        self.assertFalse(pt.is_chinese_name("ラグタイムレコード"))       # 假名 = 日文名
        self.assertFalse(pt.is_chinese_name("Void"))                  # 没汉字
        self.assertFalse(pt.is_chinese_name("这首歌不该只在我的循环列表里发光"))  # 太长
        self.assertFalse(pt.is_chinese_name("挺好听的，推荐一下。"))      # 一句话
        self.assertFalse(pt.is_chinese_name(""))

    def test_clean_name_strips_decorations(self):
        self.assertEqual("忧蓝情结", pt.clean_name("【中文字幕】忧蓝情结"))
        self.assertEqual("涅槃", pt.clean_name("《涅槃》"))
        self.assertEqual("涅槃", pt.clean_name("涅槃 feat. 重音テト"))

    def test_chinese_from_title_prefers_the_name_next_to_the_japanese(self):
        """实测：`【中文字幕】忧蓝情结/ブルー・マニアック feat.初音ミク【ナルネア】`。"""
        title = "【中文字幕】忧蓝情结/ブルー・マニアック feat.初音ミク【ナルネア】"
        self.assertEqual(("忧蓝情结", True), pt.chinese_from_title(title, "ブルー・マニアック"))

    def test_chinese_from_title_drops_the_producer_name(self):
        """`ネハン / 雄之助 feat. 重音テトSV` 是 N 站本家的写法，里面没有中文名。"""
        self.assertEqual(("", False),
                         pt.chinese_from_title("ネハン / 雄之助 feat. 重音テトSV", "ネハン", "雄之助"))

    def test_chinese_from_title_drops_noise_segments(self):
        title = "【中日歌词】indigo la End『ワールプール』自制PV"
        self.assertEqual(("", False), pt.chinese_from_title(title, "ワープループ"))

    def test_chinese_from_netease_wants_a_matching_entry(self):
        """只有「自己名字里有这首歌」或「署名里有这个 P主」的条目才算对得上。"""
        matched = {"name": "ネハン (feat. 重音テト)", "artists": [{"name": "雄之助"}],
                   "transNames": ["涅槃"]}
        self.assertEqual(["涅槃"], pt.chinese_from_netease(matched, "ネハン", "雄之助"))
        # 搜「さよなら天才」实测会返回一堆无关的歌（网易云按相关度硬凑）
        unrelated = {"name": "Chase The Wind", "artists": [{"name": "コア"}]}
        self.assertEqual([], pt.chinese_from_netease(unrelated, "さよなら天才", "雄之助"))

    def test_chinese_from_netease_reads_alias_and_chinese_name(self):
        """网易云上有的条目直接写中文名（名字里没有日文原名），只能靠 P主 认。"""
        item = {"name": "揉揉头", "artists": [{"name": "はるまきごはん"}], "alias": ["アタマモミ"]}
        self.assertEqual(["揉揉头"], pt.chinese_from_netease(item, "アタマモミ", "はるまきごはん"))

    def test_chinese_from_netease_needs_a_whole_name(self):
        """用户 2026-09 报的：搜「ぽい」时网易云返回《神っぽいな》的条目，不能拿它的译名。

        实测：`ぽい in 神っぽいな` 成立（`っぽいな` 里就有 `ぽい`），旧实现于是把
        《神っぽいな》的 `transNames = 像神一样呐` 当成《ぽい》的中文名。
        """
        cover = {"name": "神っぽいな (feat. 重音テト) [Cover]",
                 "artists": [{"name": "タカオカミズキ"}, {"name": "重音テト"}],
                 "transNames": ["像神明一样呢"]}
        original = {"name": "神っぽいな", "artists": [{"name": "ピノキオピー"}],
                    "transNames": ["像神一样呐"]}
        self.assertEqual([], pt.chinese_from_netease(cover, "ぽい", "読谷あかね"))
        self.assertEqual([], pt.chinese_from_netease(original, "ぽい", "読谷あかね"))
        # 真的是它 → 照旧收（`ぽい (feat. 初音ミク)` 里 `ぽい` 后面跟的是空格）
        mine = {"name": "ぽい (feat. 初音ミク)", "artists": [{"name": "雨良"}],
                "transNames": ["丢"]}
        self.assertEqual(["丢"], pt.chinese_from_netease(mine, "ぽい", "雨良"))

    def test_chinese_from_title_ignores_titles_without_the_song(self):
        """标题里没出现这首歌的名字时，一个候选都不给（`神っぽいな` 不是《ぽい》的标题）。"""
        self.assertEqual(("", False), pt.chinese_from_title("神っぽいな", "ぽい"))
        self.assertEqual(("", False), pt.chinese_from_title("神っぽいな/像神一样呐", "ぽい"))
        # 真写了这首歌的标题照旧能抽出紧邻的中文名
        self.assertEqual(("丢", True), pt.chinese_from_title("ぽい/丢", "ぽい"))

    def test_pick_candidate_needs_wiki_verification_for_bilibili(self):
        """b 站标题里抽出来的名字必须核实：实测 さよなら天才 的标题能抽出「高潮部分真的好棒」。"""
        candidates = [("高潮部分真的好棒", pt.SOURCE_BILIBILI, 2)]
        self.assertIsNone(pt.pick_candidate(candidates, {}, "さよなら天才"))
        # 站上真有这个歌曲条目、而且就是这首歌 → 才认
        verified = {"再见天才": "{{标题替换|{{lj|さよなら天才}}}}\n{{VOCALOID Songbox}}\n正文"}
        self.assertEqual(("再见天才", pt.SOURCE_BILIBILI),
                         pt.pick_candidate([("再见天才", pt.SOURCE_BILIBILI, 2)], verified,
                                           "さよなら天才"))
        # 页面存在但不是歌曲条目（榜单页 / P主页面）→ 不算
        self.assertIsNone(pt.pick_candidate([("高潮部分真的好棒", pt.SOURCE_BILIBILI, 2)],
                                            {"高潮部分真的好棒": "{{Producer_Song}}"},
                                            "さよなら天才"))

    def test_pick_candidate_needs_the_page_to_be_this_song(self):
        """用户 2026-09 报的：《リボン》被填成 `迷途孩子的缎带` —— 那是个真条目，但不是这首歌。"""
        texts = {"迷途孩子的缎带": "{{标题替换|{{lj|迷途のリボン}}}}\n{{VOCALOID Songbox}}"}
        self.assertIsNone(pt.pick_candidate([("迷途孩子的缎带", pt.SOURCE_BILIBILI, 2)],
                                            texts, "リボン"))
        self.assertIsNone(pt.pick_candidate([("迷途孩子的缎带", pt.SOURCE_NETEASE, 3)],
                                            texts, "リボン"))

    def test_pick_candidate_takes_netease_name_without_verification(self):
        """网易云的结构化译名（transNames / alias）可以直接用。"""
        candidates = [("忧蓝情结", pt.SOURCE_NETEASE, 3)]
        self.assertEqual(("忧蓝情结", pt.SOURCE_NETEASE),
                         pt.pick_candidate(candidates, {}, "ブルー・マニアック"))

    def test_pick_candidate_prefers_the_verified_page(self):
        candidates = [("忧蓝情结", pt.SOURCE_NETEASE, 3), ("蓝琥珀", pt.SOURCE_BILIBILI, 1)]
        texts = {"蓝琥珀": "{{标题替换|{{lj|ブルー・マニアック}}}}\n{{VOCALOID_Songbox}}"}
        self.assertEqual(("蓝琥珀", pt.SOURCE_BILIBILI),
                         pt.pick_candidate(candidates, texts, "ブルー・マニアック"))

    def test_pick_candidate_disambiguates_a_name_taken_by_someone_else(self):
        """站上这个名字是**同名但是别人的歌** → 用消歧义名（别链到别人条目上）。"""
        taken = {"偏执狂": OTHER_PARANOIA_PAGE}
        self.assertEqual(("偏执狂(shikisai)", pt.SOURCE_NETEASE),
                         pt.pick_candidate([("偏执狂", pt.SOURCE_NETEASE, 3)], taken,
                                           "パラノイア", ["shikisai"]))
        # P主 对得上（就是这首歌）→ 照旧用本名
        mine = {"偏执狂": "{{标题替换|パラノイア}}\n{{VOCALOID Songbox\n"
                         "|歌曲名称 = {{lj|パラノイア}}\n|P主 = [[shikisai]]\n}}"}
        self.assertEqual(("偏执狂", pt.SOURCE_NETEASE),
                         pt.pick_candidate([("偏执狂", pt.SOURCE_NETEASE, 3)], mine,
                                           "パラノイア", ["shikisai"]))
        # 站上真的有一首同名歌的候选，比「站上没这个名字」的候选优先
        self.assertEqual(("偏执狂(shikisai)", pt.SOURCE_NETEASE),
                         pt.pick_candidate([("偏执狂", pt.SOURCE_NETEASE, 3),
                                            ("猜的名字", pt.SOURCE_BILIBILI, 3)], taken,
                                           "パラノイア", ["shikisai"]))

    def test_fill_external_names_marks_a_disambiguated_name_as_missing(self):
        songs = [pt.ProducerSong(ja="パラノイア")]
        with mock.patch.object(pt, "external_candidates",
                               return_value=[("偏执狂", pt.SOURCE_NETEASE, 3)]), \
                mock.patch.object(pt.wiki_api, "fetch_pages_text",
                                  return_value={"偏执狂": OTHER_PARANOIA_PAGE}), \
                mock.patch.object(pt.wiki_api, "redirect_targets", return_value={}):
            result = pt.fill_external_names(songs, "shikisai", producers=["shikisai"])
        self.assertEqual(1, result["filled"])
        self.assertEqual("偏执狂(shikisai)", songs[0].cn)
        self.assertFalse(songs[0].page_exists)

    def test_fill_external_names_fills_and_counts_by_source(self):
        songs = [pt.ProducerSong(ja="ネハン"), pt.ProducerSong(ja="ブルー・マニアック"),
                 pt.ProducerSong(ja="已填", cn="已填")]
        seen: List[str] = []
        with mock.patch.object(pt, "external_candidates",
                               side_effect=lambda song, artist="": {
                                   "ネハン": [("涅槃", pt.SOURCE_NETEASE, 3)],
                                   "ブルー・マニアック": [("忧蓝情结", pt.SOURCE_BILIBILI, 2)],
                               }.get(song.ja, [])), \
                mock.patch.object(pt.wiki_api, "fetch_pages_text",
                                  return_value={"涅槃": "{{标题替换|{{lj|ネハン}}}}\n"
                                                        "{{VOCALOID Songbox}}",
                                                "忧蓝情结": "{{标题替换|{{lj|别的歌}}}}\n"
                                                            "{{VOCALOID Songbox}}"}), \
                mock.patch.object(pt.wiki_api, "redirect_targets", return_value={}):
            result = pt.fill_external_names(songs, "雄之助", progress=seen.append)
        self.assertEqual(1, result["filled"])
        self.assertEqual({"网易云": 1}, result["by_source"])        # b 站那个没核实到 → 不填
        self.assertEqual("涅槃", songs[0].cn)
        self.assertTrue(songs[0].page_exists)
        self.assertEqual("", songs[1].cn)
        self.assertTrue(any("ネハン" in line for line in seen))

    def test_fill_external_names_skips_songs_that_already_have_names(self):
        songs = [pt.ProducerSong(ja="A", cn="甲"), pt.ProducerSong(ja="")]
        with mock.patch.object(pt, "external_candidates") as candidates:
            result = pt.fill_external_names(songs, "雄之助")
        candidates.assert_not_called()
        self.assertEqual(0, result["filled"])
        self.assertEqual(0, result["checked"])

    def test_netease_search_parses_songs(self):
        payload = {"code": 200, "result": {"songs": [{"name": "ネハン"}]}}
        with _patch_get({pt.NETEASE_SEARCH_API: payload}):
            self.assertEqual([{"name": "ネハン"}], pt.netease_search("ネハン"))

    def test_netease_search_swallows_errors(self):
        with mock.patch.object(pt, "http_get", side_effect=RuntimeError("boom")):
            self.assertEqual([], pt.netease_search("ネハン"))

    def test_bilibili_search_warms_cookies_and_retries_on_412(self):
        """实测：不带 cookie 时接口直接 412（返回 HTML），带上 `buvid3` 才是 JSON。"""
        calls: List[str] = []
        payloads = [{"code": -412, "message": "请求被拦截"},
                    {"code": 0, "data": {"result": [{"title": "涅槃/ネハン"}]}}]

        def fake_get(url, use_proxy=False, params=None, timeout=None, **kwargs):
            calls.append(url)
            if url == pt.BILIBILI_HOME:
                return _Response("<html/>", cookies={"buvid3": "abc", "b_nut": "1"})
            return _Response(payloads.pop(0))

        with mock.patch.object(pt, "http_get", side_effect=fake_get):
            self.assertEqual(["涅槃/ネハン"], pt.bilibili_search("ネハン"))
        # 预热 → 搜索（412）→ 重新预热 → 搜索（成功）
        self.assertEqual([pt.BILIBILI_HOME, pt.BILIBILI_SEARCH_API,
                          pt.BILIBILI_HOME, pt.BILIBILI_SEARCH_API], calls)

    def test_bilibili_cookies_are_warmed_once(self):
        calls: List[str] = []

        def fake_get(url, use_proxy=False, params=None, timeout=None, **kwargs):
            calls.append(url)
            if url == pt.BILIBILI_HOME:
                return _Response("<html/>", cookies={"buvid3": "abc"})
            return _Response({"code": 0, "data": {"result": []}})

        with mock.patch.object(pt, "http_get", side_effect=fake_get):
            pt.bilibili_search("A")
            pt.bilibili_search("B")
        # 两个关键词只预热一次（原来每首多一次请求）
        self.assertEqual([pt.BILIBILI_HOME, pt.BILIBILI_SEARCH_API,
                          pt.BILIBILI_SEARCH_API], calls)


class BuildTemplateTest(unittest.TestCase):
    def _work(self) -> pt.ProducerWork:
        return pt.ProducerWork(
            artist=pt.ProducerArtist(id=1, name="雄之助"),
            songs=[pt.ProducerSong(ja="天堂", cn="天堂中文", date="2024-08-28"),
                   pt.ProducerSong(ja="Navy", date="2024-01-05"),
                   pt.ProducerSong(ja="ラグタイムレコード", cn="时滞记录", date="2021-09-01"),
                   pt.ProducerSong(ja="没日期")],
            albums=["Void", "Pathos"], page_name="雄之助", template_name="雄之助")

    def test_song_link_forms(self):
        self.assertEqual(pt.ProducerSong(ja="天堂", cn="天堂中文").link(), "天堂中文{{!}}{{lj|天堂}}")
        self.assertEqual(pt.ProducerSong(ja="Navy").link(), "Navy")
        self.assertEqual(pt.ProducerSong(ja="ラグタイムレコード").link(), "ラグタイムレコード")
        self.assertEqual(pt.ProducerSong(ja="", cn="只有中文").link(), "只有中文")

    def test_build_song_groups(self):
        groups = pt.build_song_groups(self._work().songs)
        self.assertEqual([label for label, _ in groups], ["2021", "2024", "其他"])
        self.assertEqual([len(songs) for _label, songs in groups], [1, 2, 1])

    def test_style_params(self):
        params = pt.style_params({**pt.DEFAULT_STYLES, "listBg": "#FFF", "listFg": ""})
        self.assertEqual(params["titlestyle"], "background:#94ceda;color:#006cad")
        self.assertEqual(params["liststyle"], "background:#FFF")
        self.assertEqual(pt.style_params({"titleBg": "", "titleFg": ""})["titlestyle"], "")

    def test_build_template_structure(self):
        text = pt.build_template(self._work())
        self.assertIn("[[分类:P主模板]]", text)
        self.assertIn("|name=雄之助", text)
        self.assertIn("|title={{colorlink|#006cad|雄之助}}", text)
        self.assertIn("{{#ifeq:{{{1}}}|collapsed", text)
        self.assertIn("|titlestyle = background:#94ceda;color:#006cad", text)
        self.assertIn("|group1 = 投稿的</br>原创曲目", text)
        self.assertIn("|list1 = {{Navbox_subgroup", text)
        self.assertIn("|list1 = {{lj|{{links|时滞记录{{!}}{{lj|ラグタイムレコード}}}}}}", text)
        self.assertIn("|list2 = {{lj|{{links|Navy|天堂中文{{!}}{{lj|天堂}}}}}}", text)
        self.assertIn("|group3 = 其他", text)
        self.assertIn("|group2 = 专辑", text)
        self.assertIn("|list2 = {{lj|{{linksplit|c=#|prefix=雄之助|Void|Pathos}}}}", text)
        self.assertEqual(text.count("{{"), text.count("}}"))       # 花括号配平

    def test_build_template_without_albums_or_songs(self):
        work = pt.ProducerWork(artist=pt.ProducerArtist(id=1, name="某人"))
        text = pt.build_template(work)
        self.assertNotIn("专辑", text)
        self.assertNotIn("Navbox_subgroup", text)
        self.assertIn("|name=某人", text)
        self.assertEqual(text.count("{{"), text.count("}}"))

    def test_title_uses_cj_for_japanese_names(self):
        """用户 2026-09 要求：标题栏的名字是日文（有假名）就用 `{{Cj}}`。

        实测 `Template:Cj` = `<span style="color:…">{{lang|ja|…}}</span>`，
        参数顺序与 `{{colorlink}}` 一致；站上 `Template:Yomitan Akane` 写的就是
        `|title={{Cj|#ffffff|読谷あかね}}`。
        """
        self.assertEqual("{{Cj|#ffffff|読谷あかね}}", pt.title_template("読谷あかね", "#ffffff"))
        self.assertEqual("{{colorlink|#ffffff|Ruliea}}", pt.title_template("Ruliea", "#ffffff"))
        self.assertEqual("{{colorlink|#006cad|雄之助}}", pt.title_template("雄之助", "#006cad"))
        self.assertEqual("{{colorlink|#006cad|}}", pt.title_template("", "#006cad"))

    def test_build_template_with_a_japanese_producer_name(self):
        """P主 名是日文时：标题用 Cj；条目名不一样时链接带上显示名。"""
        work = pt.ProducerWork(artist=pt.ProducerArtist(id=120604, name="読谷あかね"),
                               songs=[pt.ProducerSong(ja="ぽい", date="2026-06-26")],
                               page_name="Yomitan Akane", template_name="Yomitan Akane")
        text = pt.build_template(work)
        self.assertIn("此模板用于记录[[Yomitan Akane|読谷あかね]]的作品。", text)
        self.assertIn("|title={{Cj|#006cad|読谷あかね}}", text)
        self.assertIn("|name=Yomitan Akane", text)              # 模板名还是条目名
        self.assertEqual(text.count("{{"), text.count("}}"))

    def test_build_template_links_the_page_without_a_display_name(self):
        work = pt.ProducerWork(artist=pt.ProducerArtist(id=1, name="雄之助"),
                               page_name="雄之助", template_name="雄之助")
        self.assertIn("此模板用于记录[[雄之助]]的作品。", pt.build_template(work))

    def test_template_links(self):
        text = pt.build_template(self._work())
        self.assertEqual(pt.template_links(text),
                         ["时滞记录", "Navy", "天堂中文", "没日期"])
        self.assertNotIn("Void", pt.template_links(text))          # 专辑是 linksplit，不算条目


class InsertTemplateTest(unittest.TestCase):
    """插到哪儿 —— 三篇真实编辑（用户 2026-10 手改过的版本）当基准。

    之前写错了：把新模板放在 `== 注释 ==` **标题上方**，而站上（以及用户手改后的版本）是
    放在**小节里**、`<references/>` 后面；注释标题上方那一串大家族模板还要一并挪进小节。
    """

    def test_insert_into_the_note_section_after_references(self):
        text = "正文\n\n== 注释与外部链接 ==\n<references/>\n{{szri}}\n"
        new_text, note = pt.insert_template(text, "Ruliea")
        self.assertEqual(new_text,
                         "正文\n\n== 注释与外部链接 ==\n<references/>\n{{Ruliea}}\n{{szri}}\n")
        self.assertIn("<references/> 后面", note)

    def test_call_argument_writes_the_parameters(self):
        """歌姬模板往歌曲条目里写的是 `{{重音Teto/2024|nocate=1}}`（子页 + 参数）。"""
        text = "正文\n\n== 注释 ==\n<references/>\n"
        new_text, note = pt.insert_template(text, "重音Teto/2024", call="重音Teto/2024|nocate=1")
        self.assertEqual(new_text, "正文\n\n== 注释 ==\n<references/>\n"
                                   "{{重音Teto/2024|nocate=1}}\n")
        self.assertIn("<references/> 后面", note)
        # 已经写过（不管带不带参数）就不再动
        again, note = pt.insert_template(new_text, "重音Teto/2024", call="重音Teto/2024|nocate=1")
        self.assertEqual(new_text, again)
        self.assertIn("已包含", note)

    def test_insert_into_pages_passes_the_call(self):
        with mock.patch.object(pt.wiki_api, "fetch_pages_text",
                               return_value={"A": "正文\n\n== 注释 ==\n<references/>\n"}), \
                mock.patch.object(pt.wiki_api, "edit_page",
                                  return_value={"ok": True}) as edit:
            pt.insert_into_pages("重音Teto/2024", ["A"], call="重音Teto/2024|nocate=1")
        self.assertIn("{{重音Teto/2024|nocate=1}}", edit.call_args[0][1])

    def test_family_templates_above_the_heading_are_moved_down(self):
        """注释标题上方的大家族模板一并挪进小节，新模板插在**整串前面**。

        用户 2026-09-29 在 `2代目閻魔` 试了三次（中间 251489 → 最后 251574 → 最前 251587），
        最后定在整串**最前面**（紧跟 `<references/>`）。`{{clear}}` 这种排版模板不算
        大家族模板，留在原处。
        """
        text = ("正文\n\n{{-}}\n\n{{clear}}\n{{NurseRobot TypeT}}\n"
                "{{The VOCALOID Collection2025冬}}\n== 注释与外部链接 ==\n<references/>\n")
        new_text, note = pt.insert_template(text, "Ruliea")
        self.assertEqual(
            new_text,
            "正文\n\n{{-}}\n\n{{clear}}\n\n== 注释与外部链接 ==\n<references/>\n"
            "{{Ruliea}}\n{{NurseRobot TypeT}}\n{{The VOCALOID Collection2025冬}}\n")
        self.assertIn("2 个大家族模板", note)
        self.assertIn("排在它们前面", note)

    def test_family_templates_already_in_the_section_stay_in_front(self):
        """那串模板**本来就在小节里**时，新模板插在整串前面（紧跟 `<references/>`）。

        站上实测（咕呶呶 / 厚颜无耻的报酬系统 / 向灭绝问好 / Last dinner …）都是这样。
        """
        text = ("正文\n\n== 注释与外部链接 ==\n<references/>\n"
                "{{重音Teto/2026}}\n{{The VOCALOID Collection2026夏}}\n")
        new_text, note = pt.insert_template(text, "Yomitan Akane")
        self.assertEqual(
            new_text,
            "正文\n\n== 注释与外部链接 ==\n<references/>\n{{Yomitan Akane}}\n"
            "{{重音Teto/2026}}\n{{The VOCALOID Collection2026夏}}\n")
        self.assertIn("<references/> 后面", note)
        self.assertNotIn("挪了进来", note)

    def test_note_section_without_references(self):
        text = "正文\n\n== 注释 ==\n{{P主|collapsed}}\n"
        new_text, note = pt.insert_template(text, "新P主")
        self.assertEqual(new_text, "正文\n\n== 注释 ==\n{{新P主}}\n{{P主|collapsed}}\n")
        self.assertIn("注释小节里", note)

    def test_real_edit_second_enma_puts_the_new_template_first(self):
        """实测回放 `2代目閻魔`：原版（revid 207226）+ 本工具 == 用户手改的 251587（逐字节）。

        注释标题上方是 `{{重音Teto/2024|nocate=1}}` / `{{重音Teto/2026|nocate=1}}`；
        用户 2026-09-29 把它们挪进小节后，把新模板 `{{Yomitan Akane}}` 放在了**整串最前面**
        （中间试过 251574 排在最后，14:50 又改回最前）。
        """
        original = (
            "da da\n\n\n}}\n\n"
            "{{重音Teto/2024|nocate=1}}\n{{重音Teto/2026|nocate=1}}\n\n"
            "== 注释与外部链接 ==\n<references/>\n\n"
            "[[分类:日本音乐作品]]\n[[Category:使用Synthesizer V的歌曲]]\n"
            "[[Category:重音Teto歌曲]]\n[[Category:日语歌曲]]\n")
        expected = (
            "da da\n\n\n}}\n\n"
            "== 注释与外部链接 ==\n<references/>\n"
            "{{Yomitan Akane}}\n{{重音Teto/2024|nocate=1}}\n{{重音Teto/2026|nocate=1}}\n\n"
            "[[分类:日本音乐作品]]\n[[Category:使用Synthesizer V的歌曲]]\n"
            "[[Category:重音Teto歌曲]]\n[[Category:日语歌曲]]\n")
        new_text, note = pt.insert_template(original, "Yomitan Akane")
        self.assertEqual(expected, new_text)
        self.assertIn("排在它们前面", note)

    def test_insert_when_no_note_section(self):
        new_text, note = pt.insert_template("正文\n", "新P主")
        self.assertEqual(new_text, "正文\n\n{{新P主}}\n")
        self.assertIn("没有注释小节", note)

    def test_insert_without_note_section_goes_above_the_family_templates(self):
        """没有注释小节、末尾是大家族模板 + 分类行时，新模板插在**整串模板上面**。

        实测 虽然是人类。：用户手改后的版本（revid 251458）就是 `{{Ruliea}}` 在
        `{{The VOCALOID Collection2026夏}}` 之上；2026-09 之前插到了它下面（revid 251450）。
        一串模板也**不拆散**：整串一起落到新模板下面。
        """
        text = ("正文\n\n{{晴一番}}\n{{The VOCALOID Collection2024冬}}\n\n"
                "[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n")
        new_text, note = pt.insert_template(text, "雄之助")
        self.assertEqual(
            new_text,
            "正文\n\n{{雄之助}}\n{{晴一番}}\n{{The VOCALOID Collection2024冬}}\n\n"
            "[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n")
        self.assertIn("末尾大家族模板上方", note)
        # 末尾没有大家族模板时才插到分类行上方
        text = "正文\n\n[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n"
        new_text, note = pt.insert_template(text, "雄之助")
        self.assertEqual(new_text,
                         "正文\n\n{{雄之助}}\n\n[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n")
        self.assertIn("分类行上方", note)
        # 分类行夹在中间（后面还有正文）时不算「末尾的分类」，照旧追加到末尾
        text = "正文\n[[分类:甲]]\n还有正文\n"
        self.assertTrue(pt.insert_template(text, "雄之助")[0].endswith("{{雄之助}}\n"))

    def test_layout_templates_stay_put_without_a_note_section(self):
        """`{{clear}}` 这类排版模板不算大家族模板（与注释小节那一路一致）。"""
        text = "正文\n\n{{clear}}\n\n[[分类:日本音乐作品]]\n"
        new_text, note = pt.insert_template(text, "雄之助")
        self.assertEqual(new_text, "正文\n\n{{clear}}\n\n{{雄之助}}\n\n[[分类:日本音乐作品]]\n")
        self.assertIn("分类行上方", note)

    def test_skip_when_already_there(self):
        for text in ("正文\n{{雄之助}}\n== 注释 ==\n", "正文\n{{雄之助|collapsed}}\n== 注释 ==\n"):
            new_text, note = pt.insert_template(text, "雄之助")
            self.assertEqual(new_text, text)
            self.assertIn("已包含", note)

    def test_skip_when_already_there_with_prefix(self):
        text = "正文\n{{雄之助}}\n== 注释 ==\n"
        new_text, note = pt.insert_template(text, "Template:雄之助")
        self.assertEqual(new_text, text)

    def test_empty_inputs(self):
        self.assertEqual(pt.insert_template("", "X")[0], "")
        self.assertEqual(pt.insert_template("正文", "")[0], "正文")

    def test_note_heading_variants(self):
        for heading in ("== 注释 ==", "==注释==", "=== 注解 ===", "== 注释与外部链接 ==",
                        "== 参考 =="):
            text = f"正文\n\n{heading}\n<references/>\n"
            new_text, _ = pt.insert_template(text, "P主模板")
            self.assertEqual(new_text,
                             f"正文\n\n{heading}\n<references/>\n{{{{P主模板}}}}\n", heading)
        # 只有「外部链接」时不算注释小节 → 追加到末尾
        text = "正文\n\n== 外部链接 ==\n* x\n"
        new_text, note = pt.insert_template(text, "P主模板")
        self.assertTrue(new_text.endswith("{{P主模板}}\n"))

    def test_real_edits_replay_exactly(self):
        """与用户手改后的四篇（再见天才 / 曾想与你对称 / Last dinner / 虽然是人类。）逐字节一致。

        每篇的「原版」就是 User:人间百态 编辑之前的版本
        （revid 210953 / 221270 / 247542 / 248762），
        「正确版」是用户随后手改的版本（251453 / 251457 / 251451 / 251458）；这里是它们的正文尾部。

        实测 虽然是人类。 全篇回放也是内容逐字节一致（只差 MediaWiki 去掉的行尾那一个换行）：
        旧逻辑（插到分类行上方）写出来的就是用户报的 revid 251450。
        ⚠️ 再见天才 那一篇的**模板顺序**现在跟站上不同：站上那个顺序（`{{NurseRobot TypeT}}` /
        `{{Ruliea}}` / `{{The VOCALOID Collection2025冬}}`）是当时工具插的、用户 06:43 那次只挪了
        标题；用户 13:50–14:50 在 `2代目閻魔` 试了三次位置（中间 251489 → 最后 251574 →
        最前 251587），最后定在**整串最前面**，所以这里按新规则（新模板紧跟 `<references/>`）
        写基准。
        """
        cases = [
            # 再见天才：两个大家族模板在注释标题上方（新模板排在整串最前面）
            ("…\n}}\n{{NurseRobot TypeT}}\n{{The VOCALOID Collection2025冬}}\n"
             "== 注释与外部链接 ==\n<references/>\n[[分类:日本音乐作品]]\n",
             "…\n}}\n\n== 注释与外部链接 ==\n<references/>\n"
             "{{Ruliea}}\n{{NurseRobot TypeT}}\n{{The VOCALOID Collection2025冬}}\n\n"
             "[[分类:日本音乐作品]]\n"),
            # 曾想与你对称：注释小节里已经有一个大家族模板
            ("…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{szri}}\n"
             "{{NurseRobot_TypeT|collapsed}}\n[[分类:日本音乐作品]]\n",
             "…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{Ruliea}}\n{{szri}}\n"
             "{{NurseRobot_TypeT|collapsed}}\n\n[[分类:日本音乐作品]]\n"),
            # Last dinner：注释小节里有一个模板，且分类前本来就空了一行
            ("…\n}}\n\n== 注释与外部链接 ==\n<references/>\n"
             "{{The VOCALOID Collection2024冬}}\n\n[[分类:日本音乐作品]]\n",
             "…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{Ruliea}}\n"
             "{{The VOCALOID Collection2024冬}}\n\n[[分类:日本音乐作品]]\n"),
            # 虽然是人类。：**没有**注释小节，末尾是大家族模板 + 分类行
            ("…\n}}\n\n{{The VOCALOID Collection2026夏}}\n\n"
             "[[Category:日本音乐作品]]\n[[Category:初音未来歌曲]]\n",
             "…\n}}\n\n{{Ruliea}}\n{{The VOCALOID Collection2026夏}}\n\n"
             "[[Category:日本音乐作品]]\n[[Category:初音未来歌曲]]\n"),
        ]
        for original, expected in cases:
            new_text, _note = pt.insert_template(original, "Ruliea")
            self.assertEqual(new_text, expected)


class InsertIntoPagesTest(unittest.TestCase):
    def test_insert_into_pages(self):
        texts = {"时滞记录": "正文\n\n{{P主|collapsed}}\n== 注释 ==\n<references/>\n",
                 "Navy": "正文\n\n{{雄之助}}\n== 注释 ==\n"}
        edited = []
        seen = []
        with mock.patch.object(pt.wiki_api, "fetch_pages_text", return_value=texts), \
                mock.patch.object(pt.wiki_api, "edit_page",
                                  side_effect=lambda title, text, summary="": edited.append(title)
                                  or {"ok": True}):
            results = pt.insert_into_pages("雄之助", ["时滞记录", "Navy", "不存在"], seen.append)
        self.assertEqual([r["title"] for r in results], ["时滞记录", "Navy", "不存在"])
        self.assertTrue(results[0]["ok"])
        self.assertEqual(results[1]["count"], 0)                 # 已经有了
        self.assertFalse(results[2]["ok"])
        self.assertEqual(edited, ["时滞记录"])
        self.assertEqual(len(seen), 3)

    def test_insert_into_pages_reports_edit_failure(self):
        with mock.patch.object(pt.wiki_api, "fetch_pages_text",
                               return_value={"A": "正文\n== 注释 ==\n"}), \
                mock.patch.object(pt.wiki_api, "edit_page",
                                  return_value={"ok": False, "error": "被权限挡住"}):
            results = pt.insert_into_pages("P主", ["A"])
        self.assertFalse(results[0]["ok"])
        self.assertIn("权限", results[0]["error"])


if __name__ == "__main__":
    unittest.main()
