"""`utils/producer_template.py` 的单测：HTTP / 维基全部 mock，不联网。"""
import json
import unittest
from unittest import mock

from utils import producer_template as pt


class _Response:
    def __init__(self, payload):
        self.text = json.dumps(payload) if not isinstance(payload, str) else payload
        self.status_code = 200

    def raise_for_status(self):
        return None


def _patch_get(routes):
    """按 url 前缀分发假响应；返回 mock 出来的 `http_get`。"""

    def fake_get(url, use_proxy=False, params=None, timeout=None, **kwargs):
        for prefix, payload in routes.items():
            if url.startswith(prefix):
                if callable(payload):
                    return _Response(payload(params or {}))
                return _Response(payload)
        raise AssertionError(f"没准备好这个地址的假响应：{url}")

    return mock.patch.object(pt, "http_get", side_effect=fake_get)


SONG_ITEM = {
    "id": 1, "defaultName": "天堂", "artistString": "雄之助 feat. 初音ミク",
    "publishDate": "2024-08-28T00:00:00Z", "songType": "Original",
}


class ParseHelpersTest(unittest.TestCase):
    def test_clean_title(self):
        self.assertEqual(pt.clean_title("{{lj|ループメモリー}}"), "ループメモリー")
        self.assertEqual(pt.clean_title("{{lj|[[时滞记录|ラグタイムレコード]]}}"), "ラグタイムレコード")
        self.assertEqual(pt.clean_title("[[中文|日文]]"), "日文")
        self.assertEqual(pt.clean_title("超新星{{!}}Supernova"), "超新星")
        self.assertEqual(pt.clean_title("<!--\n-->Navy<!--\n-->"), "Navy")
        self.assertEqual(pt.clean_title("'''粗体'''"), "粗体")

    def test_template_calls_handles_nesting(self):
        text = "{{lj|{{links|A{{!}}B|C}}}}"
        self.assertEqual(pt.template_calls(text, "links"), ["A{{!}}B|C"])

    def test_split_args_ignores_nested_pipes(self):
        self.assertEqual(pt.split_args("A{{!}}B|{{lj|C}}|D"), ["A{{!}}B", "{{lj|C}}", "D"])

    def test_parse_publish_date(self):
        self.assertEqual(pt.parse_publish_date("2026-08-28T00:00:00Z"), "2026-08-28")
        self.assertEqual(pt.parse_publish_date("2024-08"), "2024-08")
        self.assertEqual(pt.parse_publish_date("2024"), "2024")
        self.assertEqual(pt.parse_publish_date(None), "")
        self.assertEqual(pt.parse_publish_date("不是日期"), "")

    def test_parse_artist_id(self):
        self.assertEqual(pt.parse_artist_id("23981"), 23981)
        self.assertEqual(pt.parse_artist_id("https://vocadb.net/Artist/Details/23981"), 23981)
        self.assertEqual(pt.parse_artist_id("雄之助"), 0)


class AutoUploadTest(unittest.TestCase):
    """只有发行商代传的 YouTube 自动投稿的曲子不收（用户 2026-10 要求）。

    实测 S/950828（ワープループ）：唯一的 PV 是 `author = "Yunosuke - Topic"`、
    简介 `Provided to YouTube by NexTone Inc. … Auto-generated by YouTube.`。
    """

    TOPIC = {"service": "Youtube", "author": "Yunosuke - Topic",
             "description": "Provided to YouTube by NexTone Inc.\n\nワープループ\n\n"
                            "Auto-generated by YouTube."}
    REAL = {"service": "NicoNicoDouga", "author": "雄之助", "description": "新曲です"}

    def test_is_auto_upload(self):
        self.assertTrue(pt.is_auto_upload(self.TOPIC))
        self.assertTrue(pt.is_auto_upload({"author": "雄之助 - Topic"}))
        self.assertTrue(pt.is_auto_upload({"description": "Provided to YouTube by X"}))
        self.assertTrue(pt.is_auto_upload({"description": "Auto-generated by YouTube."}))
        self.assertFalse(pt.is_auto_upload(self.REAL))
        self.assertFalse(pt.is_auto_upload({}))

    def test_has_real_pv(self):
        self.assertFalse(pt.has_real_pv({"pvs": [self.TOPIC]}))
        self.assertTrue(pt.has_real_pv({"pvs": [self.TOPIC, self.REAL]}))   # 混着就保留
        self.assertTrue(pt.has_real_pv({"pvs": [self.REAL]}))
        self.assertTrue(pt.has_real_pv({}))                                   # 没信息就不删

    def test_fetch_songs_skips_auto_upload_only_songs(self):
        payload = {"items": [
            {**SONG_ITEM, "id": 1, "defaultName": "ワープループ", "pvs": [self.TOPIC]},
            {**SONG_ITEM, "id": 2, "defaultName": "ネハン",
             "pvs": [self.TOPIC, self.REAL]},
            {**SONG_ITEM, "id": 3, "defaultName": "没有 PV 信息"},
        ]}
        with _patch_get({pt.VOCADB_SONG_URL: payload}):
            songs = pt.fetch_songs(23981)
        self.assertEqual(["ネハン", "没有 PV 信息"], [song.ja for song in songs])


class OwnAlbumTest(unittest.TestCase):
    """合辑 / 多艺人发行 / 只是挂名支持的专辑不收（用户 2026-10 要求）。"""

    def test_various_artists_is_not_ours(self):
        # Al/55475「音速を超えて」、Al/54757「NIGHT HIKE Compilation Vol.1」
        for name in ("音速を超えて", "NIGHT HIKE Compilation Vol.1"):
            self.assertFalse(pt.is_own_album(
                {"name": name, "artistString": "Various artists", "artists": [
                    {"artist": {"id": 23981}, "isSupport": False, "roles": "Default"}]},
                23981))

    def test_support_only_credits_are_not_ours(self):
        self.assertFalse(pt.is_own_album(
            {"name": "hologram", "artistString": "Ruliea feat. various", "artists": [
                {"artist": {"id": 123110}, "isSupport": False, "roles": "Default"},
                {"artist": {"id": 23981}, "isSupport": True, "roles": "Arranger"}]},
            23981))

    def test_own_albums_are_kept(self):
        self.assertTrue(pt.is_own_album(
            {"name": "Void", "artistString": "雄之助 feat. various", "artists": [
                {"artist": {"id": 23981}, "isSupport": False, "roles": "Default"}]},
            23981))
        # 没有 artistString / artists 时一律保留（宁可多留，不要误删）
        self.assertTrue(pt.is_own_album({"name": "Void"}, 23981))
        # 艺人列表里没有他 → 也不能因此当作「只是挂名」
        self.assertTrue(pt.is_own_album(
            {"name": "Void", "artistString": "Yunosuke",
             "artists": [{"artist": {"id": 999}, "isSupport": False}]}, 23981))

    def test_fetch_albums_filters_and_dedupes(self):
        payload = {"items": [
            {"name": "Void", "releaseDate": {"year": 2025},
             "artistString": "雄之助 feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "音速を超えて", "releaseDate": {"year": 2026},
             "artistString": "Various artists",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "hologram", "releaseDate": {"year": 2024},
             "artistString": "Ruliea feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": True}]},
            {"name": "Pathos", "releaseDate": {"year": 2016},
             "artistString": "雄之助, 攻 feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "Void", "releaseDate": {"year": 2025},
             "artistString": "雄之助 feat. various",
             "artists": [{"artist": {"id": 23981}, "isSupport": False}]},
            {"name": "", "releaseDate": {"year": 2020}},
        ]}
        with _patch_get({pt.VOCADB_ALBUM_URL: payload}) as get:
            albums = pt.fetch_albums(23981)
        self.assertEqual(["Pathos", "Void"], albums)
        self.assertEqual("Album", get.call_args.kwargs["params"]["discTypes"])
        self.assertEqual(23981, get.call_args.kwargs["params"]["artistId[]"])
        self.assertIn("Artists", get.call_args.kwargs["params"]["fields"])


class VocaDbTest(unittest.TestCase):
    def test_search_artists_by_name(self):
        payload = {"items": [{"id": 23981, "name": "雄之助", "artistType": "Producer",
                              "additionalNames": "Yunosuke"}]}
        with _patch_get({pt.VOCADB_ARTIST_URL: payload}) as get:
            artists = pt.search_artists("雄之助")
        self.assertEqual(len(artists), 1)
        self.assertEqual(artists[0].id, 23981)
        self.assertEqual(artists[0].name_en, "Yunosuke")
        # 名字搜索走 query，不该带 artistId
        self.assertEqual(get.call_args.kwargs["params"]["query"], "雄之助")

    def test_search_artists_by_url_goes_to_details(self):
        payload = {"id": 23981, "name": "雄之助", "artistType": "Producer"}
        with _patch_get({f"{pt.VOCADB_ARTIST_URL}/23981": payload}) as get:
            artists = pt.search_artists("https://vocadb.net/Artist/Details/23981")
        self.assertEqual(artists[0].name, "雄之助")
        self.assertTrue(get.call_args.args[0].endswith("/artists/23981"))

    def test_search_artists_empty_query(self):
        self.assertEqual(pt.search_artists("  "), [])

    def test_fetch_songs_uses_array_param_and_sorts(self):
        pages = {}

        def handler(params):
            pages["params"] = params
            return {"items": [SONG_ITEM,
                              {**SONG_ITEM, "id": 2, "defaultName": "早安",
                               "publishDate": "2020-01-01T00:00:00Z"}]}

        with _patch_get({pt.VOCADB_SONG_URL: handler}):
            songs = pt.fetch_songs(23981)
        self.assertEqual([s.ja for s in songs], ["早安", "天堂"])       # 按日期从早到晚
        self.assertEqual(pages["params"]["artistId[]"], 23981)
        self.assertEqual(pages["params"]["songTypes"], "Original")
        self.assertEqual(pages["params"]["onlyWithPvs"], "true")
        self.assertNotIn("artistId", pages["params"])                # 写成 artistId 会被静默忽略

    def test_fetch_songs_dedupes_and_pages(self):
        calls = []

        def handler(params):
            calls.append(params["start"])
            if params["start"] == 0:
                return {"items": [SONG_ITEM] * 100}
            return {"items": [{**SONG_ITEM, "id": 3, "defaultName": "再来",
                               "publishDate": "2026-01-01T00:00:00Z"}]}

        with _patch_get({pt.VOCADB_SONG_URL: handler}):
            songs = pt.fetch_songs(23981)
        self.assertEqual(calls, [0, 100])
        self.assertEqual([s.ja for s in songs], ["天堂", "再来"])

    def test_fetch_works_without_artist(self):
        with _patch_get({pt.VOCADB_ARTIST_URL: {"items": []}}):
            work = pt.fetch_works("不存在的人")
        self.assertEqual(work.songs, [])
        self.assertEqual(work.artist.name, "")


class ProducerPageTest(unittest.TestCase):
    PAGE = """== 歌曲 ==
{{Producer_Song
|nnd_id   = sm45871877
|作曲     = {{lj|はるまきごはん}}
|投稿日期 = 2025年8月21日
|条目     = 揉揉头
|标题     = {{lj|アタマモミ}}
|image    = x.jpg
}}

{{Producer_Song
|条目     = 时滞记录
|标题     = {{lj|[[时滞记录|ラグタイムレコード]]}}
}}

* 专辑：《[[#Void|Void]]》与 [[#Pathos|Pathos]]
{{lj|[[银河录|{{lj|銀河録}}]]}}
"""

    def test_parse_producer_page(self):
        mapping = pt.parse_producer_page(self.PAGE)
        self.assertEqual(mapping["アタマモミ"], "揉揉头")
        self.assertEqual(mapping["ラグタイムレコード"], "时滞记录")
        self.assertEqual(mapping["銀河録"], "银河录")
        self.assertNotIn("Void", mapping)          # `[[#Void|Void]]` 是专辑小节，不是条目
        self.assertNotIn("Pathos", mapping)

    def test_apply_wiki_names(self):
        songs = [pt.ProducerSong(ja="アタマモミ"), pt.ProducerSong(ja="未知的歌"),
                 pt.ProducerSong(ja="アタマモミ", cn="已填的")]
        filled = pt.apply_wiki_names(songs, {"アタマモミ": "揉揉头"})
        self.assertEqual(filled, 1)
        self.assertEqual(songs[0].cn, "揉揉头")
        self.assertEqual(songs[2].cn, "已填的")     # 已经填过的不覆盖

    def test_merge_page_songs_adds_wiki_only_songs(self):
        work = pt.ProducerWork(songs=[pt.ProducerSong(ja="アタマモミ", date="2025-08-21")])
        pt._merge_page_songs(work, self.PAGE)
        names = [s.ja for s in work.songs]
        self.assertIn("ラグタイムレコード", names)          # 页面上有、VocaDB 没给
        self.assertEqual(names.count("アタマモミ"), 1)      # 重复的不再加一遍
        added = [s for s in work.songs if s.ja == "ラグタイムレコード"][0]
        self.assertEqual(added.source, "wiki")

    def test_mark_existing_fills_chinese_name(self):
        songs = [pt.ProducerSong(ja="ラグタイムレコード"), pt.ProducerSong(ja="不存在")]
        pt.mark_existing(songs, {"时滞记录": "正文"})
        self.assertFalse(songs[0].page_exists)
        pt.mark_existing([pt.ProducerSong(ja="タイトル")], {"タイトル": "正文"})
        songs = [pt.ProducerSong(ja="ラグタイムレコード", cn="时滞记录")]
        pt.mark_existing(songs, {"时滞记录": "正文"})
        self.assertTrue(songs[0].page_exists)

    def test_resolve_from_wiki(self):
        work = pt.ProducerWork(artist=pt.ProducerArtist(id=1, name="雄之助"),
                               songs=[pt.ProducerSong(ja="ラグタイムレコード"),
                                      pt.ProducerSong(ja="Navy")])
        texts = {"雄之助": self.PAGE, "时滞记录": "正文", "Navy": "正文"}
        with mock.patch.object(pt.wiki_api, "fetch_pages_text",
                               side_effect=lambda titles: {t: texts[t] for t in titles
                                                           if t in texts}):
            pt.resolve_from_wiki(work)
        self.assertEqual(work.page_name, "雄之助")
        by_ja = {song.ja: song for song in work.songs}
        self.assertEqual(by_ja["ラグタイムレコード"].cn, "时滞记录")
        self.assertEqual(by_ja["アタマモミ"].cn, "揉揉头")          # 从 P主条目里补进来的
        self.assertEqual(by_ja["アタマモミ"].date, "2025-08-21")   # 日期也来自 {{Producer_Song}}

    def test_search_page_by_song_prefers_page_with_japanese_name(self):
        result = [("雄之助", "别的"), ("时滞记录", "ラグタイムレコード 是这首歌")]
        with mock.patch.object(pt.wiki_api, "search_pages_with_text",
                               return_value=result):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")),
                             "时滞记录")
        with mock.patch.object(pt.wiki_api, "search_pages_with_text", return_value=[]):
            self.assertEqual(pt.search_page_by_song(pt.ProducerSong(ja="ラグタイムレコード")), "")

    def test_fill_missing_names(self):
        songs = [pt.ProducerSong(ja="已填", cn="已填"), pt.ProducerSong(ja="要找"),
                 pt.ProducerSong(ja="找不到")]
        seen = []
        with mock.patch.object(pt, "search_page_by_song",
                               side_effect=lambda song: "找到的页" if song.ja == "要找" else ""):
            filled = pt.fill_missing_names(songs, progress=seen.append)
        self.assertEqual(filled, 1)
        self.assertEqual(songs[1].cn, "找到的页")
        self.assertTrue(any("要找" in line for line in seen))


class BuildTemplateTest(unittest.TestCase):
    def _work(self) -> pt.ProducerWork:
        return pt.ProducerWork(
            artist=pt.ProducerArtist(id=1, name="雄之助"),
            songs=[pt.ProducerSong(ja="天堂", cn="天堂中文", date="2024-08-28"),
                   pt.ProducerSong(ja="Navy", date="2024-01-05"),
                   pt.ProducerSong(ja="ラグタイムレコード", cn="时滞记录", date="2021-09-01"),
                   pt.ProducerSong(ja="没日期")],
            albums=["Void", "Pathos"], page_name="雄之助", template_name="雄之助")

    def test_song_link_forms(self):
        self.assertEqual(pt.ProducerSong(ja="天堂", cn="天堂中文").link(), "天堂中文{{!}}{{lj|天堂}}")
        self.assertEqual(pt.ProducerSong(ja="Navy").link(), "Navy")
        self.assertEqual(pt.ProducerSong(ja="ラグタイムレコード").link(), "ラグタイムレコード")
        self.assertEqual(pt.ProducerSong(ja="", cn="只有中文").link(), "只有中文")

    def test_build_song_groups(self):
        groups = pt.build_song_groups(self._work().songs)
        self.assertEqual([label for label, _ in groups], ["2021", "2024", "其他"])
        self.assertEqual([len(songs) for _label, songs in groups], [1, 2, 1])

    def test_style_params(self):
        params = pt.style_params({**pt.DEFAULT_STYLES, "listBg": "#FFF", "listFg": ""})
        self.assertEqual(params["titlestyle"], "background:#94ceda;color:#006cad")
        self.assertEqual(params["liststyle"], "background:#FFF")
        self.assertEqual(pt.style_params({"titleBg": "", "titleFg": ""})["titlestyle"], "")

    def test_build_template_structure(self):
        text = pt.build_template(self._work())
        self.assertIn("[[分类:P主模板]]", text)
        self.assertIn("|name=雄之助", text)
        self.assertIn("|title={{colorlink|#006cad|雄之助}}", text)
        self.assertIn("{{#ifeq:{{{1}}}|collapsed", text)
        self.assertIn("|titlestyle = background:#94ceda;color:#006cad", text)
        self.assertIn("|group1 = 投稿的<br>原创曲目", text)
        self.assertIn("|list1 = {{Navbox_subgroup", text)
        self.assertIn("|list1 = {{lj|{{links|时滞记录{{!}}{{lj|ラグタイムレコード}}}}}}", text)
        self.assertIn("|list2 = {{lj|{{links|Navy|天堂中文{{!}}{{lj|天堂}}}}}}", text)
        self.assertIn("|group3 = 其他", text)
        self.assertIn("|group2 = 专辑", text)
        self.assertIn("|list2 = {{lj|{{linksplit|c=#|prefix=雄之助|Void|Pathos}}}}", text)
        self.assertEqual(text.count("{{"), text.count("}}"))       # 花括号配平

    def test_build_template_without_albums_or_songs(self):
        work = pt.ProducerWork(artist=pt.ProducerArtist(id=1, name="某人"))
        text = pt.build_template(work)
        self.assertNotIn("专辑", text)
        self.assertNotIn("Navbox_subgroup", text)
        self.assertIn("|name=某人", text)
        self.assertEqual(text.count("{{"), text.count("}}"))

    def test_template_links(self):
        text = pt.build_template(self._work())
        self.assertEqual(pt.template_links(text),
                         ["时滞记录", "Navy", "天堂中文", "没日期"])
        self.assertNotIn("Void", pt.template_links(text))          # 专辑是 linksplit，不算条目


class InsertTemplateTest(unittest.TestCase):
    """插到哪儿 —— 三篇真实编辑（用户 2026-10 手改过的版本）当基准。

    之前写错了：把新模板放在 `== 注释 ==` **标题上方**，而站上（以及用户手改后的版本）是
    放在**小节里**、`<references/>` 后面；注释标题上方那一串大家族模板还要一并挪进小节。
    """

    def test_insert_into_the_note_section_after_references(self):
        text = "正文\n\n== 注释与外部链接 ==\n<references/>\n{{szri}}\n"
        new_text, note = pt.insert_template(text, "Ruliea")
        self.assertEqual(new_text,
                         "正文\n\n== 注释与外部链接 ==\n<references/>\n{{Ruliea}}\n{{szri}}\n")
        self.assertIn("<references/> 后面", note)

    def test_family_templates_above_the_heading_are_moved_down(self):
        """注释标题上方的大家族模板一并挪进小节，新模板插在「最靠近标题的那一行」上面。

        `{{clear}}` 这种排版模板不算大家族模板，留在原处。
        """
        text = ("正文\n\n{{-}}\n\n{{clear}}\n{{NurseRobot TypeT}}\n"
                "{{The VOCALOID Collection2025冬}}\n== 注释与外部链接 ==\n<references/>\n")
        new_text, note = pt.insert_template(text, "Ruliea")
        self.assertEqual(
            new_text,
            "正文\n\n{{-}}\n\n{{clear}}\n\n== 注释与外部链接 ==\n<references/>\n"
            "{{NurseRobot TypeT}}\n{{Ruliea}}\n{{The VOCALOID Collection2025冬}}\n")
        self.assertIn("2 个大家族模板", note)

    def test_note_section_without_references(self):
        text = "正文\n\n== 注释 ==\n{{P主|collapsed}}\n"
        new_text, note = pt.insert_template(text, "新P主")
        self.assertEqual(new_text, "正文\n\n== 注释 ==\n{{新P主}}\n{{P主|collapsed}}\n")
        self.assertIn("注释小节里", note)

    def test_insert_when_no_note_section(self):
        new_text, note = pt.insert_template("正文\n", "新P主")
        self.assertEqual(new_text, "正文\n\n{{新P主}}\n")
        self.assertIn("没有注释小节", note)

    def test_insert_without_note_section_goes_above_categories(self):
        """没有注释小节、末尾又摆着分类行时插到**分类上方**（分类按惯例在最末尾）。

        实测 カクレミノ 就是这样：`{{晴一番}}…` + `[[分类:…]]`，没有 `== 注释 ==`。
        """
        text = ("正文\n\n{{晴一番}}\n{{The VOCALOID Collection2024冬}}\n"
                "[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n")
        new_text, note = pt.insert_template(text, "雄之助")
        self.assertEqual(
            new_text,
            "正文\n\n{{晴一番}}\n{{The VOCALOID Collection2024冬}}\n{{雄之助}}\n\n"
            "[[分类:日本音乐作品]]\n[[Category:日语歌曲]]\n")
        self.assertIn("分类行上方", note)
        # 分类行夹在中间（后面还有正文）时不算「末尾的分类」，照旧追加到末尾
        text = "正文\n[[分类:甲]]\n还有正文\n"
        self.assertTrue(pt.insert_template(text, "雄之助")[0].endswith("{{雄之助}}\n"))

    def test_skip_when_already_there(self):
        for text in ("正文\n{{雄之助}}\n== 注释 ==\n", "正文\n{{雄之助|collapsed}}\n== 注释 ==\n"):
            new_text, note = pt.insert_template(text, "雄之助")
            self.assertEqual(new_text, text)
            self.assertIn("已包含", note)

    def test_skip_when_already_there_with_prefix(self):
        text = "正文\n{{雄之助}}\n== 注释 ==\n"
        new_text, note = pt.insert_template(text, "Template:雄之助")
        self.assertEqual(new_text, text)

    def test_empty_inputs(self):
        self.assertEqual(pt.insert_template("", "X")[0], "")
        self.assertEqual(pt.insert_template("正文", "")[0], "正文")

    def test_note_heading_variants(self):
        for heading in ("== 注释 ==", "==注释==", "=== 注解 ===", "== 注释与外部链接 ==",
                        "== 参考 =="):
            text = f"正文\n\n{heading}\n<references/>\n"
            new_text, _ = pt.insert_template(text, "P主模板")
            self.assertEqual(new_text,
                             f"正文\n\n{heading}\n<references/>\n{{{{P主模板}}}}\n", heading)
        # 只有「外部链接」时不算注释小节 → 追加到末尾
        text = "正文\n\n== 外部链接 ==\n* x\n"
        new_text, note = pt.insert_template(text, "P主模板")
        self.assertTrue(new_text.endswith("{{P主模板}}\n"))

    def test_real_edits_replay_exactly(self):
        """与用户手改后的三篇（再见天才 / 曾想与你对称 / Last dinner）逐字节一致。

        每篇的「原版」就是 User:人间百态 编辑之前的版本（revid 210953 / 221270 / 247542），
        「正确版」是用户随后手改的版本（251453 / 251457 / 251451）；这里是它们的正文尾部。
        """
        cases = [
            # 再见天才：两个大家族模板在注释标题上方
            ("…\n}}\n{{NurseRobot TypeT}}\n{{The VOCALOID Collection2025冬}}\n"
             "== 注释与外部链接 ==\n<references/>\n[[分类:日本音乐作品]]\n",
             "…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{NurseRobot TypeT}}\n"
             "{{Ruliea}}\n{{The VOCALOID Collection2025冬}}\n\n[[分类:日本音乐作品]]\n"),
            # 曾想与你对称：注释小节里已经有一个大家族模板
            ("…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{szri}}\n"
             "{{NurseRobot_TypeT|collapsed}}\n[[分类:日本音乐作品]]\n",
             "…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{Ruliea}}\n{{szri}}\n"
             "{{NurseRobot_TypeT|collapsed}}\n\n[[分类:日本音乐作品]]\n"),
            # Last dinner：注释小节里有一个模板，且分类前本来就空了一行
            ("…\n}}\n\n== 注释与外部链接 ==\n<references/>\n"
             "{{The VOCALOID Collection2024冬}}\n\n[[分类:日本音乐作品]]\n",
             "…\n}}\n\n== 注释与外部链接 ==\n<references/>\n{{Ruliea}}\n"
             "{{The VOCALOID Collection2024冬}}\n\n[[分类:日本音乐作品]]\n"),
        ]
        for original, expected in cases:
            new_text, _note = pt.insert_template(original, "Ruliea")
            self.assertEqual(new_text, expected)


class InsertIntoPagesTest(unittest.TestCase):
    def test_insert_into_pages(self):
        texts = {"时滞记录": "正文\n\n{{P主|collapsed}}\n== 注释 ==\n<references/>\n",
                 "Navy": "正文\n\n{{雄之助}}\n== 注释 ==\n"}
        edited = []
        seen = []
        with mock.patch.object(pt.wiki_api, "fetch_pages_text", return_value=texts), \
                mock.patch.object(pt.wiki_api, "edit_page",
                                  side_effect=lambda title, text, summary="": edited.append(title)
                                  or {"ok": True}):
            results = pt.insert_into_pages("雄之助", ["时滞记录", "Navy", "不存在"], seen.append)
        self.assertEqual([r["title"] for r in results], ["时滞记录", "Navy", "不存在"])
        self.assertTrue(results[0]["ok"])
        self.assertEqual(results[1]["count"], 0)                 # 已经有了
        self.assertFalse(results[2]["ok"])
        self.assertEqual(edited, ["时滞记录"])
        self.assertEqual(len(seen), 3)

    def test_insert_into_pages_reports_edit_failure(self):
        with mock.patch.object(pt.wiki_api, "fetch_pages_text",
                               return_value={"A": "正文\n== 注释 ==\n"}), \
                mock.patch.object(pt.wiki_api, "edit_page",
                                  return_value={"ok": False, "error": "被权限挡住"}):
            results = pt.insert_into_pages("P主", ["A"])
        self.assertFalse(results[0]["ok"])
        self.assertIn("权限", results[0]["error"])


if __name__ == "__main__":
    unittest.main()
